services:
  # 1. Database (Không Forward public)
  db:
    image: postgres:16-alpine
    container_name: invoice_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: invoice_management
    ports:
      - "5432:5432"
    volumes:
      # Lưu dữ liệu vào thư mục 'postgres_data' ngay cạnh file này
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck: # Đảm bảo DB sẵn sàng trước khi Backend chạy
      test: ["CMD-SHELL", "pg_isready -U admin -d invoice_management"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Backend Go (Internal)
  backend:
    build: haideptrai2707/invoice_app_backend:v1
    container_name: invoice_backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: 123
      DB_NAME: invoice_management
    expose:
      - "5432"

  # 3. Frontend Web (Forward public)
  gateway: # Đây chính là con Nginx làm Gateway
    image: nginx:alpine
    container_name: invoice_gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount code frontend đã build sẵn và file cấu hình Nginx
      - ./invoice_app_frontend/build/web:/usr/share/nginx/html
      # Mount file cấu hình Nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # Mount chứng chỉ SSL
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend