// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: global_settings.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getGlobalSettings = `-- name: GetGlobalSettings :one
SELECT id, global_settings_file
FROM global_settings
WHERE is_singleton = TRUE
LIMIT 1
`

type GetGlobalSettingsRow struct {
	ID                 uuid.UUID       `json:"id"`
	GlobalSettingsFile json.RawMessage `json:"global_settings_file"`
}

func (q *Queries) GetGlobalSettings(ctx context.Context) (GetGlobalSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, getGlobalSettings)
	var i GetGlobalSettingsRow
	err := row.Scan(&i.ID, &i.GlobalSettingsFile)
	return i, err
}

const insertGlobalSettings = `-- name: InsertGlobalSettings :one
INSERT INTO global_settings (global_settings_file)
VALUES ($1)
ON CONFLICT (is_singleton) DO NOTHING
RETURNING id, global_settings_file
`

type InsertGlobalSettingsRow struct {
	ID                 uuid.UUID       `json:"id"`
	GlobalSettingsFile json.RawMessage `json:"global_settings_file"`
}

func (q *Queries) InsertGlobalSettings(ctx context.Context, globalSettingsFile json.RawMessage) (InsertGlobalSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, insertGlobalSettings, globalSettingsFile)
	var i InsertGlobalSettingsRow
	err := row.Scan(&i.ID, &i.GlobalSettingsFile)
	return i, err
}

const updateGlobalSettings = `-- name: UpdateGlobalSettings :one
UPDATE global_settings
SET global_settings_file = $1
WHERE is_singleton = TRUE
RETURNING id, global_settings_file
`

type UpdateGlobalSettingsRow struct {
	ID                 uuid.UUID       `json:"id"`
	GlobalSettingsFile json.RawMessage `json:"global_settings_file"`
}

func (q *Queries) UpdateGlobalSettings(ctx context.Context, globalSettingsFile json.RawMessage) (UpdateGlobalSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, updateGlobalSettings, globalSettingsFile)
	var i UpdateGlobalSettingsRow
	err := row.Scan(&i.ID, &i.GlobalSettingsFile)
	return i, err
}
