// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoice.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createBuyer = `-- name: CreateBuyer :one
INSERT INTO buyers (
    buyer_code,
    buyer_name,
    address,
    phone_number,
    id_card_number,
    email,
    tax_id,
    lat,
    lng
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING buyer_id, buyer_code, buyer_name, address, phone_number, id_card_number, email, tax_id, lat, lng, is_active, created_at, updated_at, deleted_at
`

type CreateBuyerParams struct {
	BuyerCode    string          `json:"buyer_code"`
	BuyerName    string          `json:"buyer_name"`
	Address      sql.NullString  `json:"address"`
	PhoneNumber  sql.NullString  `json:"phone_number"`
	IDCardNumber sql.NullString  `json:"id_card_number"`
	Email        sql.NullString  `json:"email"`
	TaxID        sql.NullString  `json:"tax_id"`
	Lat          sql.NullFloat64 `json:"lat"`
	Lng          sql.NullFloat64 `json:"lng"`
}

func (q *Queries) CreateBuyer(ctx context.Context, arg CreateBuyerParams) (Buyer, error) {
	row := q.db.QueryRowContext(ctx, createBuyer,
		arg.BuyerCode,
		arg.BuyerName,
		arg.Address,
		arg.PhoneNumber,
		arg.IDCardNumber,
		arg.Email,
		arg.TaxID,
		arg.Lat,
		arg.Lng,
	)
	var i Buyer
	err := row.Scan(
		&i.BuyerID,
		&i.BuyerCode,
		&i.BuyerName,
		&i.Address,
		&i.PhoneNumber,
		&i.IDCardNumber,
		&i.Email,
		&i.TaxID,
		&i.Lat,
		&i.Lng,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
    device_holding_id,
    device_name
) VALUES (
    $1, $2
) ON CONFLICT (device_holding_id) DO UPDATE 
SET device_name = EXCLUDED.device_name
RETURNING device_holding_id, device_name
`

type CreateDeviceParams struct {
	DeviceHoldingID string         `json:"device_holding_id"`
	DeviceName      sql.NullString `json:"device_name"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice, arg.DeviceHoldingID, arg.DeviceName)
	var i Device
	err := row.Scan(&i.DeviceHoldingID, &i.DeviceName)
	return i, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    account_id,
    buyer_id,
    invoice_code,
    total_amount,
    device_holding_id,
    edit_status,
    buyer_name_snapshot,
    address_snapshot,
    phone_number_snapshot,
    id_card_number_snapshot,
    email_snapshot,
    tax_id_snapshot,
    lat_snapshot,
    lng_snapshot
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING invoice_id, account_id, buyer_id, invoice_code, total_amount, device_holding_id, edit_status, paid_locked, buyer_name_snapshot, address_snapshot, id_card_number_snapshot, email_snapshot, lat_snapshot, lng_snapshot, phone_number_snapshot, tax_id_snapshot, is_active, created_at, updated_at, deleted_at
`

type CreateInvoiceParams struct {
	AccountID            uuid.NullUUID   `json:"account_id"`
	BuyerID              uuid.NullUUID   `json:"buyer_id"`
	InvoiceCode          string          `json:"invoice_code"`
	TotalAmount          int64           `json:"total_amount"`
	DeviceHoldingID      sql.NullString  `json:"device_holding_id"`
	EditStatus           sql.NullBool    `json:"edit_status"`
	BuyerNameSnapshot    sql.NullString  `json:"buyer_name_snapshot"`
	AddressSnapshot      sql.NullString  `json:"address_snapshot"`
	PhoneNumberSnapshot  sql.NullString  `json:"phone_number_snapshot"`
	IDCardNumberSnapshot sql.NullString  `json:"id_card_number_snapshot"`
	EmailSnapshot        sql.NullString  `json:"email_snapshot"`
	TaxIDSnapshot        sql.NullString  `json:"tax_id_snapshot"`
	LatSnapshot          sql.NullFloat64 `json:"lat_snapshot"`
	LngSnapshot          sql.NullFloat64 `json:"lng_snapshot"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, createInvoice,
		arg.AccountID,
		arg.BuyerID,
		arg.InvoiceCode,
		arg.TotalAmount,
		arg.DeviceHoldingID,
		arg.EditStatus,
		arg.BuyerNameSnapshot,
		arg.AddressSnapshot,
		arg.PhoneNumberSnapshot,
		arg.IDCardNumberSnapshot,
		arg.EmailSnapshot,
		arg.TaxIDSnapshot,
		arg.LatSnapshot,
		arg.LngSnapshot,
	)
	var i Invoice
	err := row.Scan(
		&i.InvoiceID,
		&i.AccountID,
		&i.BuyerID,
		&i.InvoiceCode,
		&i.TotalAmount,
		&i.DeviceHoldingID,
		&i.EditStatus,
		&i.PaidLocked,
		&i.BuyerNameSnapshot,
		&i.AddressSnapshot,
		&i.IDCardNumberSnapshot,
		&i.EmailSnapshot,
		&i.LatSnapshot,
		&i.LngSnapshot,
		&i.PhoneNumberSnapshot,
		&i.TaxIDSnapshot,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createLineItem = `-- name: CreateLineItem :one
INSERT INTO line_items (
    invoice_id,
    item_id,
    unit_id,
    quantity,
    unit_price_custom,
    sub_total,
    item_name_snapshot,
    unit_name_snapshot,
    position_key
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING line_item_id, invoice_id, item_id, unit_id, quantity, unit_price_custom, sub_total, item_name_snapshot, unit_name_snapshot, position_key, created_at
`

type CreateLineItemParams struct {
	InvoiceID        uuid.NullUUID  `json:"invoice_id"`
	ItemID           uuid.NullUUID  `json:"item_id"`
	UnitID           uuid.NullUUID  `json:"unit_id"`
	Quantity         int32          `json:"quantity"`
	UnitPriceCustom  sql.NullInt64  `json:"unit_price_custom"`
	SubTotal         int64          `json:"sub_total"`
	ItemNameSnapshot sql.NullString `json:"item_name_snapshot"`
	UnitNameSnapshot sql.NullString `json:"unit_name_snapshot"`
	PositionKey      string         `json:"position_key"`
}

func (q *Queries) CreateLineItem(ctx context.Context, arg CreateLineItemParams) (LineItem, error) {
	row := q.db.QueryRowContext(ctx, createLineItem,
		arg.InvoiceID,
		arg.ItemID,
		arg.UnitID,
		arg.Quantity,
		arg.UnitPriceCustom,
		arg.SubTotal,
		arg.ItemNameSnapshot,
		arg.UnitNameSnapshot,
		arg.PositionKey,
	)
	var i LineItem
	err := row.Scan(
		&i.LineItemID,
		&i.InvoiceID,
		&i.ItemID,
		&i.UnitID,
		&i.Quantity,
		&i.UnitPriceCustom,
		&i.SubTotal,
		&i.ItemNameSnapshot,
		&i.UnitNameSnapshot,
		&i.PositionKey,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBuyer = `-- name: DeleteBuyer :exec
UPDATE buyers
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE buyer_id = $1
`

func (q *Queries) DeleteBuyer(ctx context.Context, buyerID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteBuyer, buyerID)
	return err
}

const deleteInvoice = `-- name: DeleteInvoice :exec
UPDATE invoices
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE invoice_id = $1
`

func (q *Queries) DeleteInvoice(ctx context.Context, invoiceID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteInvoice, invoiceID)
	return err
}

const deleteLineItem = `-- name: DeleteLineItem :exec
DELETE FROM line_items
WHERE line_item_id = $1
`

func (q *Queries) DeleteLineItem(ctx context.Context, lineItemID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteLineItem, lineItemID)
	return err
}

const getBuyerByCode = `-- name: GetBuyerByCode :one
SELECT buyer_id, buyer_code, buyer_name, address, phone_number, id_card_number, email, tax_id, lat, lng, is_active, created_at, updated_at, deleted_at FROM buyers
WHERE buyer_code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBuyerByCode(ctx context.Context, buyerCode string) (Buyer, error) {
	row := q.db.QueryRowContext(ctx, getBuyerByCode, buyerCode)
	var i Buyer
	err := row.Scan(
		&i.BuyerID,
		&i.BuyerCode,
		&i.BuyerName,
		&i.Address,
		&i.PhoneNumber,
		&i.IDCardNumber,
		&i.Email,
		&i.TaxID,
		&i.Lat,
		&i.Lng,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBuyerByID = `-- name: GetBuyerByID :one
SELECT buyer_id, buyer_code, buyer_name, address, phone_number, id_card_number, email, tax_id, lat, lng, is_active, created_at, updated_at, deleted_at FROM buyers
WHERE buyer_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBuyerByID(ctx context.Context, buyerID uuid.UUID) (Buyer, error) {
	row := q.db.QueryRowContext(ctx, getBuyerByID, buyerID)
	var i Buyer
	err := row.Scan(
		&i.BuyerID,
		&i.BuyerCode,
		&i.BuyerName,
		&i.Address,
		&i.PhoneNumber,
		&i.IDCardNumber,
		&i.Email,
		&i.TaxID,
		&i.Lat,
		&i.Lng,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT device_holding_id, device_name FROM devices
WHERE device_holding_id = $1
`

func (q *Queries) GetDeviceByID(ctx context.Context, deviceHoldingID string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByID, deviceHoldingID)
	var i Device
	err := row.Scan(&i.DeviceHoldingID, &i.DeviceName)
	return i, err
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT i.invoice_id, i.account_id, i.buyer_id, i.invoice_code, i.total_amount, i.device_holding_id, i.edit_status, i.paid_locked, i.buyer_name_snapshot, i.address_snapshot, i.id_card_number_snapshot, i.email_snapshot, i.lat_snapshot, i.lng_snapshot, i.phone_number_snapshot, i.tax_id_snapshot, i.is_active, i.created_at, i.updated_at, i.deleted_at, b.buyer_code
FROM invoices i
LEFT JOIN buyers b ON i.buyer_id = b.buyer_id
WHERE i.invoice_id = $1 AND i.deleted_at IS NULL
`

type GetInvoiceByIDRow struct {
	InvoiceID            uuid.UUID       `json:"invoice_id"`
	AccountID            uuid.NullUUID   `json:"account_id"`
	BuyerID              uuid.NullUUID   `json:"buyer_id"`
	InvoiceCode          string          `json:"invoice_code"`
	TotalAmount          int64           `json:"total_amount"`
	DeviceHoldingID      sql.NullString  `json:"device_holding_id"`
	EditStatus           sql.NullBool    `json:"edit_status"`
	PaidLocked           sql.NullBool    `json:"paid_locked"`
	BuyerNameSnapshot    sql.NullString  `json:"buyer_name_snapshot"`
	AddressSnapshot      sql.NullString  `json:"address_snapshot"`
	IDCardNumberSnapshot sql.NullString  `json:"id_card_number_snapshot"`
	EmailSnapshot        sql.NullString  `json:"email_snapshot"`
	LatSnapshot          sql.NullFloat64 `json:"lat_snapshot"`
	LngSnapshot          sql.NullFloat64 `json:"lng_snapshot"`
	PhoneNumberSnapshot  sql.NullString  `json:"phone_number_snapshot"`
	TaxIDSnapshot        sql.NullString  `json:"tax_id_snapshot"`
	IsActive             sql.NullBool    `json:"is_active"`
	CreatedAt            sql.NullTime    `json:"created_at"`
	UpdatedAt            sql.NullTime    `json:"updated_at"`
	DeletedAt            sql.NullTime    `json:"deleted_at"`
	BuyerCode            sql.NullString  `json:"buyer_code"`
}

func (q *Queries) GetInvoiceByID(ctx context.Context, invoiceID uuid.UUID) (GetInvoiceByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getInvoiceByID, invoiceID)
	var i GetInvoiceByIDRow
	err := row.Scan(
		&i.InvoiceID,
		&i.AccountID,
		&i.BuyerID,
		&i.InvoiceCode,
		&i.TotalAmount,
		&i.DeviceHoldingID,
		&i.EditStatus,
		&i.PaidLocked,
		&i.BuyerNameSnapshot,
		&i.AddressSnapshot,
		&i.IDCardNumberSnapshot,
		&i.EmailSnapshot,
		&i.LatSnapshot,
		&i.LngSnapshot,
		&i.PhoneNumberSnapshot,
		&i.TaxIDSnapshot,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.BuyerCode,
	)
	return i, err
}

const getInvoiceWithDeviceName = `-- name: GetInvoiceWithDeviceName :one
SELECT i.invoice_id, i.account_id, i.buyer_id, i.invoice_code, i.total_amount, i.device_holding_id, i.edit_status, i.paid_locked, i.buyer_name_snapshot, i.address_snapshot, i.id_card_number_snapshot, i.email_snapshot, i.lat_snapshot, i.lng_snapshot, i.phone_number_snapshot, i.tax_id_snapshot, i.is_active, i.created_at, i.updated_at, i.deleted_at, d.device_name
FROM invoices i
LEFT JOIN devices d ON i.device_holding_id = d.device_holding_id
WHERE i.invoice_id = $1 AND i.deleted_at IS NULL
`

type GetInvoiceWithDeviceNameRow struct {
	InvoiceID            uuid.UUID       `json:"invoice_id"`
	AccountID            uuid.NullUUID   `json:"account_id"`
	BuyerID              uuid.NullUUID   `json:"buyer_id"`
	InvoiceCode          string          `json:"invoice_code"`
	TotalAmount          int64           `json:"total_amount"`
	DeviceHoldingID      sql.NullString  `json:"device_holding_id"`
	EditStatus           sql.NullBool    `json:"edit_status"`
	PaidLocked           sql.NullBool    `json:"paid_locked"`
	BuyerNameSnapshot    sql.NullString  `json:"buyer_name_snapshot"`
	AddressSnapshot      sql.NullString  `json:"address_snapshot"`
	IDCardNumberSnapshot sql.NullString  `json:"id_card_number_snapshot"`
	EmailSnapshot        sql.NullString  `json:"email_snapshot"`
	LatSnapshot          sql.NullFloat64 `json:"lat_snapshot"`
	LngSnapshot          sql.NullFloat64 `json:"lng_snapshot"`
	PhoneNumberSnapshot  sql.NullString  `json:"phone_number_snapshot"`
	TaxIDSnapshot        sql.NullString  `json:"tax_id_snapshot"`
	IsActive             sql.NullBool    `json:"is_active"`
	CreatedAt            sql.NullTime    `json:"created_at"`
	UpdatedAt            sql.NullTime    `json:"updated_at"`
	DeletedAt            sql.NullTime    `json:"deleted_at"`
	DeviceName           sql.NullString  `json:"device_name"`
}

func (q *Queries) GetInvoiceWithDeviceName(ctx context.Context, invoiceID uuid.UUID) (GetInvoiceWithDeviceNameRow, error) {
	row := q.db.QueryRowContext(ctx, getInvoiceWithDeviceName, invoiceID)
	var i GetInvoiceWithDeviceNameRow
	err := row.Scan(
		&i.InvoiceID,
		&i.AccountID,
		&i.BuyerID,
		&i.InvoiceCode,
		&i.TotalAmount,
		&i.DeviceHoldingID,
		&i.EditStatus,
		&i.PaidLocked,
		&i.BuyerNameSnapshot,
		&i.AddressSnapshot,
		&i.IDCardNumberSnapshot,
		&i.EmailSnapshot,
		&i.LatSnapshot,
		&i.LngSnapshot,
		&i.PhoneNumberSnapshot,
		&i.TaxIDSnapshot,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.DeviceName,
	)
	return i, err
}

const getInvoiceWithLines = `-- name: GetInvoiceWithLines :one
SELECT i.invoice_id, i.account_id, i.buyer_id, i.invoice_code, i.total_amount, i.device_holding_id, i.edit_status, i.paid_locked, i.buyer_name_snapshot, i.address_snapshot, i.id_card_number_snapshot, i.email_snapshot, i.lat_snapshot, i.lng_snapshot, i.phone_number_snapshot, i.tax_id_snapshot, i.is_active, i.created_at, i.updated_at, i.deleted_at,
       b.buyer_code,
       COALESCE(JSON_AGG(JSONB_BUILD_OBJECT(
         'line_item_id', li.line_item_id,
         'item_id', li.item_id,
         'unit_id', li.unit_id,
         'quantity', li.quantity,
         'unit_price_custom', li.unit_price_custom,
         'sub_total', li.sub_total,
         'item_name_snapshot', li.item_name_snapshot,
         'unit_name_snapshot', li.unit_name_snapshot,
         'position_key', li.position_key
       ) ORDER BY li.position_key) FILTER (WHERE li.line_item_id IS NOT NULL), '[]')::JSONB AS line_items
FROM invoices i
LEFT JOIN buyers b ON i.buyer_id = b.buyer_id
LEFT JOIN line_items li ON i.invoice_id = li.invoice_id
WHERE i.invoice_id = $1
GROUP BY i.invoice_id, b.buyer_code
`

type GetInvoiceWithLinesRow struct {
	InvoiceID            uuid.UUID       `json:"invoice_id"`
	AccountID            uuid.NullUUID   `json:"account_id"`
	BuyerID              uuid.NullUUID   `json:"buyer_id"`
	InvoiceCode          string          `json:"invoice_code"`
	TotalAmount          int64           `json:"total_amount"`
	DeviceHoldingID      sql.NullString  `json:"device_holding_id"`
	EditStatus           sql.NullBool    `json:"edit_status"`
	PaidLocked           sql.NullBool    `json:"paid_locked"`
	BuyerNameSnapshot    sql.NullString  `json:"buyer_name_snapshot"`
	AddressSnapshot      sql.NullString  `json:"address_snapshot"`
	IDCardNumberSnapshot sql.NullString  `json:"id_card_number_snapshot"`
	EmailSnapshot        sql.NullString  `json:"email_snapshot"`
	LatSnapshot          sql.NullFloat64 `json:"lat_snapshot"`
	LngSnapshot          sql.NullFloat64 `json:"lng_snapshot"`
	PhoneNumberSnapshot  sql.NullString  `json:"phone_number_snapshot"`
	TaxIDSnapshot        sql.NullString  `json:"tax_id_snapshot"`
	IsActive             sql.NullBool    `json:"is_active"`
	CreatedAt            sql.NullTime    `json:"created_at"`
	UpdatedAt            sql.NullTime    `json:"updated_at"`
	DeletedAt            sql.NullTime    `json:"deleted_at"`
	BuyerCode            sql.NullString  `json:"buyer_code"`
	LineItems            json.RawMessage `json:"line_items"`
}

func (q *Queries) GetInvoiceWithLines(ctx context.Context, invoiceID uuid.UUID) (GetInvoiceWithLinesRow, error) {
	row := q.db.QueryRowContext(ctx, getInvoiceWithLines, invoiceID)
	var i GetInvoiceWithLinesRow
	err := row.Scan(
		&i.InvoiceID,
		&i.AccountID,
		&i.BuyerID,
		&i.InvoiceCode,
		&i.TotalAmount,
		&i.DeviceHoldingID,
		&i.EditStatus,
		&i.PaidLocked,
		&i.BuyerNameSnapshot,
		&i.AddressSnapshot,
		&i.IDCardNumberSnapshot,
		&i.EmailSnapshot,
		&i.LatSnapshot,
		&i.LngSnapshot,
		&i.PhoneNumberSnapshot,
		&i.TaxIDSnapshot,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.BuyerCode,
		&i.LineItems,
	)
	return i, err
}

const getLastBuyerCode = `-- name: GetLastBuyerCode :one
SELECT buyer_code FROM buyers
WHERE buyer_code LIKE 'KH-%'
ORDER BY buyer_code DESC
LIMIT 1
`

func (q *Queries) GetLastBuyerCode(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getLastBuyerCode)
	var buyer_code string
	err := row.Scan(&buyer_code)
	return buyer_code, err
}

const getLastInvoiceCode = `-- name: GetLastInvoiceCode :one
SELECT invoice_code FROM invoices
WHERE invoice_code LIKE $1
ORDER BY invoice_code DESC
LIMIT 1
`

func (q *Queries) GetLastInvoiceCode(ctx context.Context, invoiceCode string) (string, error) {
	row := q.db.QueryRowContext(ctx, getLastInvoiceCode, invoiceCode)
	var invoice_code string
	err := row.Scan(&invoice_code)
	return invoice_code, err
}

const getLineItemByID = `-- name: GetLineItemByID :one
SELECT line_item_id, invoice_id, item_id, unit_id, quantity, unit_price_custom, sub_total, item_name_snapshot, unit_name_snapshot, position_key, created_at FROM line_items
WHERE line_item_id = $1
`

func (q *Queries) GetLineItemByID(ctx context.Context, lineItemID uuid.UUID) (LineItem, error) {
	row := q.db.QueryRowContext(ctx, getLineItemByID, lineItemID)
	var i LineItem
	err := row.Scan(
		&i.LineItemID,
		&i.InvoiceID,
		&i.ItemID,
		&i.UnitID,
		&i.Quantity,
		&i.UnitPriceCustom,
		&i.SubTotal,
		&i.ItemNameSnapshot,
		&i.UnitNameSnapshot,
		&i.PositionKey,
		&i.CreatedAt,
	)
	return i, err
}

const listBuyers = `-- name: ListBuyers :many
SELECT buyer_id, buyer_code, buyer_name, address, phone_number, id_card_number, email, tax_id, lat, lng, is_active, created_at, updated_at, deleted_at FROM buyers
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListBuyersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBuyers(ctx context.Context, arg ListBuyersParams) ([]Buyer, error) {
	rows, err := q.db.QueryContext(ctx, listBuyers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Buyer
	for rows.Next() {
		var i Buyer
		if err := rows.Scan(
			&i.BuyerID,
			&i.BuyerCode,
			&i.BuyerName,
			&i.Address,
			&i.PhoneNumber,
			&i.IDCardNumber,
			&i.Email,
			&i.TaxID,
			&i.Lat,
			&i.Lng,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedBuyers = `-- name: ListDeletedBuyers :many
SELECT buyer_id, buyer_code, buyer_name, address, phone_number, id_card_number, email, tax_id, lat, lng, is_active, created_at, updated_at, deleted_at FROM buyers
WHERE deleted_at IS NOT NULL
ORDER BY deleted_at DESC
`

func (q *Queries) ListDeletedBuyers(ctx context.Context) ([]Buyer, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedBuyers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Buyer
	for rows.Next() {
		var i Buyer
		if err := rows.Scan(
			&i.BuyerID,
			&i.BuyerCode,
			&i.BuyerName,
			&i.Address,
			&i.PhoneNumber,
			&i.IDCardNumber,
			&i.Email,
			&i.TaxID,
			&i.Lat,
			&i.Lng,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedInvoices = `-- name: ListDeletedInvoices :many
SELECT i.invoice_id, i.account_id, i.buyer_id, i.invoice_code, i.total_amount, i.device_holding_id, i.edit_status, i.paid_locked, i.buyer_name_snapshot, i.address_snapshot, i.id_card_number_snapshot, i.email_snapshot, i.lat_snapshot, i.lng_snapshot, i.phone_number_snapshot, i.tax_id_snapshot, i.is_active, i.created_at, i.updated_at, i.deleted_at, d.device_name, b.buyer_code
FROM invoices i
LEFT JOIN devices d ON i.device_holding_id = d.device_holding_id
LEFT JOIN buyers b ON i.buyer_id = b.buyer_id
WHERE i.deleted_at IS NOT NULL
ORDER BY i.deleted_at DESC
`

type ListDeletedInvoicesRow struct {
	InvoiceID            uuid.UUID       `json:"invoice_id"`
	AccountID            uuid.NullUUID   `json:"account_id"`
	BuyerID              uuid.NullUUID   `json:"buyer_id"`
	InvoiceCode          string          `json:"invoice_code"`
	TotalAmount          int64           `json:"total_amount"`
	DeviceHoldingID      sql.NullString  `json:"device_holding_id"`
	EditStatus           sql.NullBool    `json:"edit_status"`
	PaidLocked           sql.NullBool    `json:"paid_locked"`
	BuyerNameSnapshot    sql.NullString  `json:"buyer_name_snapshot"`
	AddressSnapshot      sql.NullString  `json:"address_snapshot"`
	IDCardNumberSnapshot sql.NullString  `json:"id_card_number_snapshot"`
	EmailSnapshot        sql.NullString  `json:"email_snapshot"`
	LatSnapshot          sql.NullFloat64 `json:"lat_snapshot"`
	LngSnapshot          sql.NullFloat64 `json:"lng_snapshot"`
	PhoneNumberSnapshot  sql.NullString  `json:"phone_number_snapshot"`
	TaxIDSnapshot        sql.NullString  `json:"tax_id_snapshot"`
	IsActive             sql.NullBool    `json:"is_active"`
	CreatedAt            sql.NullTime    `json:"created_at"`
	UpdatedAt            sql.NullTime    `json:"updated_at"`
	DeletedAt            sql.NullTime    `json:"deleted_at"`
	DeviceName           sql.NullString  `json:"device_name"`
	BuyerCode            sql.NullString  `json:"buyer_code"`
}

func (q *Queries) ListDeletedInvoices(ctx context.Context) ([]ListDeletedInvoicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeletedInvoicesRow
	for rows.Next() {
		var i ListDeletedInvoicesRow
		if err := rows.Scan(
			&i.InvoiceID,
			&i.AccountID,
			&i.BuyerID,
			&i.InvoiceCode,
			&i.TotalAmount,
			&i.DeviceHoldingID,
			&i.EditStatus,
			&i.PaidLocked,
			&i.BuyerNameSnapshot,
			&i.AddressSnapshot,
			&i.IDCardNumberSnapshot,
			&i.EmailSnapshot,
			&i.LatSnapshot,
			&i.LngSnapshot,
			&i.PhoneNumberSnapshot,
			&i.TaxIDSnapshot,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeviceName,
			&i.BuyerCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEditingInvoices = `-- name: ListEditingInvoices :many
SELECT i.invoice_id, i.account_id, i.buyer_id, i.invoice_code, i.total_amount, i.device_holding_id, i.edit_status, i.paid_locked, i.buyer_name_snapshot, i.address_snapshot, i.id_card_number_snapshot, i.email_snapshot, i.lat_snapshot, i.lng_snapshot, i.phone_number_snapshot, i.tax_id_snapshot, i.is_active, i.created_at, i.updated_at, i.deleted_at, d.device_name, b.buyer_code
FROM invoices i
LEFT JOIN devices d ON i.device_holding_id = d.device_holding_id
LEFT JOIN buyers b ON i.buyer_id = b.buyer_id
WHERE i.edit_status = TRUE AND i.deleted_at IS NULL
ORDER BY i.updated_at DESC
`

type ListEditingInvoicesRow struct {
	InvoiceID            uuid.UUID       `json:"invoice_id"`
	AccountID            uuid.NullUUID   `json:"account_id"`
	BuyerID              uuid.NullUUID   `json:"buyer_id"`
	InvoiceCode          string          `json:"invoice_code"`
	TotalAmount          int64           `json:"total_amount"`
	DeviceHoldingID      sql.NullString  `json:"device_holding_id"`
	EditStatus           sql.NullBool    `json:"edit_status"`
	PaidLocked           sql.NullBool    `json:"paid_locked"`
	BuyerNameSnapshot    sql.NullString  `json:"buyer_name_snapshot"`
	AddressSnapshot      sql.NullString  `json:"address_snapshot"`
	IDCardNumberSnapshot sql.NullString  `json:"id_card_number_snapshot"`
	EmailSnapshot        sql.NullString  `json:"email_snapshot"`
	LatSnapshot          sql.NullFloat64 `json:"lat_snapshot"`
	LngSnapshot          sql.NullFloat64 `json:"lng_snapshot"`
	PhoneNumberSnapshot  sql.NullString  `json:"phone_number_snapshot"`
	TaxIDSnapshot        sql.NullString  `json:"tax_id_snapshot"`
	IsActive             sql.NullBool    `json:"is_active"`
	CreatedAt            sql.NullTime    `json:"created_at"`
	UpdatedAt            sql.NullTime    `json:"updated_at"`
	DeletedAt            sql.NullTime    `json:"deleted_at"`
	DeviceName           sql.NullString  `json:"device_name"`
	BuyerCode            sql.NullString  `json:"buyer_code"`
}

func (q *Queries) ListEditingInvoices(ctx context.Context) ([]ListEditingInvoicesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEditingInvoices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEditingInvoicesRow
	for rows.Next() {
		var i ListEditingInvoicesRow
		if err := rows.Scan(
			&i.InvoiceID,
			&i.AccountID,
			&i.BuyerID,
			&i.InvoiceCode,
			&i.TotalAmount,
			&i.DeviceHoldingID,
			&i.EditStatus,
			&i.PaidLocked,
			&i.BuyerNameSnapshot,
			&i.AddressSnapshot,
			&i.IDCardNumberSnapshot,
			&i.EmailSnapshot,
			&i.LatSnapshot,
			&i.LngSnapshot,
			&i.PhoneNumberSnapshot,
			&i.TaxIDSnapshot,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeviceName,
			&i.BuyerCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesFiltered = `-- name: ListInvoicesFiltered :many
SELECT i.invoice_id, i.account_id, i.buyer_id, i.invoice_code, i.total_amount, i.device_holding_id, i.edit_status, i.paid_locked, i.buyer_name_snapshot, i.address_snapshot, i.id_card_number_snapshot, i.email_snapshot, i.lat_snapshot, i.lng_snapshot, i.phone_number_snapshot, i.tax_id_snapshot, i.is_active, i.created_at, i.updated_at, i.deleted_at, d.device_name, b.buyer_code
FROM invoices i
LEFT JOIN devices d ON i.device_holding_id = d.device_holding_id
LEFT JOIN buyers b ON i.buyer_id = b.buyer_id
WHERE i.deleted_at IS NULL
  AND (
    ($1::boolean = FALSE AND $2::boolean = FALSE AND $3::boolean = FALSE)
    OR ($1::boolean = TRUE AND i.edit_status = TRUE)
    OR ($2::boolean = TRUE AND i.edit_status = FALSE AND i.paid_locked = FALSE)
    OR ($3::boolean = TRUE AND i.paid_locked = TRUE)
  )
  AND ($4::UUID IS NULL OR i.buyer_id = $4::UUID)
  AND ($5::text IS NULL OR my_unaccent(i.invoice_code) ILIKE my_unaccent(concat('%', $5::text, '%')))
  AND ($6::UUID IS NULL OR EXISTS (
      SELECT 1 FROM line_items li 
      WHERE li.invoice_id = i.invoice_id AND li.item_id = $6::UUID
  ))
  AND ($7::timestamptz IS NULL OR i.created_at >= $7::timestamptz)
  AND ($8::timestamptz IS NULL OR i.created_at <= $8::timestamptz)
ORDER BY 
  CASE WHEN $9::text = 'updated_at' AND $10::text = 'desc' THEN i.updated_at END DESC,
  CASE WHEN $9::text = 'updated_at' AND $10::text = 'asc' THEN i.updated_at END ASC,
  CASE WHEN $9::text = 'created_at' AND $10::text = 'desc' THEN i.created_at END DESC,
  CASE WHEN $9::text = 'created_at' AND $10::text = 'asc' THEN i.created_at END ASC,
  i.updated_at DESC
LIMIT $12
OFFSET $11
`

type ListInvoicesFilteredParams struct {
	ShowDraft   bool           `json:"show_draft"`
	ShowSaved   bool           `json:"show_saved"`
	ShowLocked  bool           `json:"show_locked"`
	BuyerID     uuid.NullUUID  `json:"buyer_id"`
	InvoiceCode sql.NullString `json:"invoice_code"`
	ItemID      uuid.NullUUID  `json:"item_id"`
	StartDate   sql.NullTime   `json:"start_date"`
	EndDate     sql.NullTime   `json:"end_date"`
	SortBy      string         `json:"sort_by"`
	SortOrder   string         `json:"sort_order"`
	OffsetVal   int32          `json:"offset_val"`
	LimitVal    int32          `json:"limit_val"`
}

type ListInvoicesFilteredRow struct {
	InvoiceID            uuid.UUID       `json:"invoice_id"`
	AccountID            uuid.NullUUID   `json:"account_id"`
	BuyerID              uuid.NullUUID   `json:"buyer_id"`
	InvoiceCode          string          `json:"invoice_code"`
	TotalAmount          int64           `json:"total_amount"`
	DeviceHoldingID      sql.NullString  `json:"device_holding_id"`
	EditStatus           sql.NullBool    `json:"edit_status"`
	PaidLocked           sql.NullBool    `json:"paid_locked"`
	BuyerNameSnapshot    sql.NullString  `json:"buyer_name_snapshot"`
	AddressSnapshot      sql.NullString  `json:"address_snapshot"`
	IDCardNumberSnapshot sql.NullString  `json:"id_card_number_snapshot"`
	EmailSnapshot        sql.NullString  `json:"email_snapshot"`
	LatSnapshot          sql.NullFloat64 `json:"lat_snapshot"`
	LngSnapshot          sql.NullFloat64 `json:"lng_snapshot"`
	PhoneNumberSnapshot  sql.NullString  `json:"phone_number_snapshot"`
	TaxIDSnapshot        sql.NullString  `json:"tax_id_snapshot"`
	IsActive             sql.NullBool    `json:"is_active"`
	CreatedAt            sql.NullTime    `json:"created_at"`
	UpdatedAt            sql.NullTime    `json:"updated_at"`
	DeletedAt            sql.NullTime    `json:"deleted_at"`
	DeviceName           sql.NullString  `json:"device_name"`
	BuyerCode            sql.NullString  `json:"buyer_code"`
}

func (q *Queries) ListInvoicesFiltered(ctx context.Context, arg ListInvoicesFilteredParams) ([]ListInvoicesFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, listInvoicesFiltered,
		arg.ShowDraft,
		arg.ShowSaved,
		arg.ShowLocked,
		arg.BuyerID,
		arg.InvoiceCode,
		arg.ItemID,
		arg.StartDate,
		arg.EndDate,
		arg.SortBy,
		arg.SortOrder,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvoicesFilteredRow
	for rows.Next() {
		var i ListInvoicesFilteredRow
		if err := rows.Scan(
			&i.InvoiceID,
			&i.AccountID,
			&i.BuyerID,
			&i.InvoiceCode,
			&i.TotalAmount,
			&i.DeviceHoldingID,
			&i.EditStatus,
			&i.PaidLocked,
			&i.BuyerNameSnapshot,
			&i.AddressSnapshot,
			&i.IDCardNumberSnapshot,
			&i.EmailSnapshot,
			&i.LatSnapshot,
			&i.LngSnapshot,
			&i.PhoneNumberSnapshot,
			&i.TaxIDSnapshot,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.DeviceName,
			&i.BuyerCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInvoice = `-- name: LockInvoice :one
UPDATE invoices
SET paid_locked = TRUE,
    edit_status = FALSE,
    updated_at = NOW()
WHERE invoice_id = $1 AND deleted_at IS NULL
RETURNING invoice_id, account_id, buyer_id, invoice_code, total_amount, device_holding_id, edit_status, paid_locked, buyer_name_snapshot, address_snapshot, id_card_number_snapshot, email_snapshot, lat_snapshot, lng_snapshot, phone_number_snapshot, tax_id_snapshot, is_active, created_at, updated_at, deleted_at
`

func (q *Queries) LockInvoice(ctx context.Context, invoiceID uuid.UUID) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, lockInvoice, invoiceID)
	var i Invoice
	err := row.Scan(
		&i.InvoiceID,
		&i.AccountID,
		&i.BuyerID,
		&i.InvoiceCode,
		&i.TotalAmount,
		&i.DeviceHoldingID,
		&i.EditStatus,
		&i.PaidLocked,
		&i.BuyerNameSnapshot,
		&i.AddressSnapshot,
		&i.IDCardNumberSnapshot,
		&i.EmailSnapshot,
		&i.LatSnapshot,
		&i.LngSnapshot,
		&i.PhoneNumberSnapshot,
		&i.TaxIDSnapshot,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const restoreBuyer = `-- name: RestoreBuyer :exec
UPDATE buyers
SET deleted_at = NULL,
    updated_at = NOW()
WHERE buyer_id = $1
`

func (q *Queries) RestoreBuyer(ctx context.Context, buyerID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, restoreBuyer, buyerID)
	return err
}

const restoreInvoice = `-- name: RestoreInvoice :exec
UPDATE invoices
SET deleted_at = NULL,
    updated_at = NOW()
WHERE invoice_id = $1
`

func (q *Queries) RestoreInvoice(ctx context.Context, invoiceID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, restoreInvoice, invoiceID)
	return err
}

const searchBuyers = `-- name: SearchBuyers :many
SELECT buyer_id, buyer_code, buyer_name, address, phone_number, id_card_number, email, tax_id, lat, lng, is_active, created_at, updated_at, deleted_at FROM buyers
WHERE deleted_at IS NULL
AND (
    my_unaccent(buyer_name) ILIKE '%' || my_unaccent($2) || '%'
    OR my_unaccent(buyer_code) ILIKE '%' || my_unaccent($2) || '%'
    OR phone_number ILIKE '%' || $2 || '%'
    OR id_card_number ILIKE '%' || $2 || '%'
    OR my_unaccent(address) ILIKE '%' || my_unaccent($2) || '%'
)
ORDER BY
    CASE WHEN buyer_code = $2 THEN 0 ELSE 1 END,
    CASE WHEN phone_number = $2 THEN 0 ELSE 1 END,
    CASE WHEN id_card_number = $2 THEN 0 ELSE 1 END,
    similarity(my_unaccent(buyer_name), my_unaccent($2)) DESC
LIMIT $1
`

type SearchBuyersParams struct {
	Limit   int32  `json:"limit"`
	Keyword string `json:"keyword"`
}

func (q *Queries) SearchBuyers(ctx context.Context, arg SearchBuyersParams) ([]Buyer, error) {
	rows, err := q.db.QueryContext(ctx, searchBuyers, arg.Limit, arg.Keyword)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Buyer
	for rows.Next() {
		var i Buyer
		if err := rows.Scan(
			&i.BuyerID,
			&i.BuyerCode,
			&i.BuyerName,
			&i.Address,
			&i.PhoneNumber,
			&i.IDCardNumber,
			&i.Email,
			&i.TaxID,
			&i.Lat,
			&i.Lng,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBuyer = `-- name: UpdateBuyer :one
UPDATE buyers
SET
    buyer_code = $2,
    buyer_name = $3,
    address = $4,
    phone_number = $5,
    id_card_number = $6,
    email = $7,
    tax_id = $8,
    lat = $9,
    lng = $10,
    updated_at = NOW()
WHERE buyer_id = $1 AND deleted_at IS NULL
RETURNING buyer_id, buyer_code, buyer_name, address, phone_number, id_card_number, email, tax_id, lat, lng, is_active, created_at, updated_at, deleted_at
`

type UpdateBuyerParams struct {
	BuyerID      uuid.UUID       `json:"buyer_id"`
	BuyerCode    string          `json:"buyer_code"`
	BuyerName    string          `json:"buyer_name"`
	Address      sql.NullString  `json:"address"`
	PhoneNumber  sql.NullString  `json:"phone_number"`
	IDCardNumber sql.NullString  `json:"id_card_number"`
	Email        sql.NullString  `json:"email"`
	TaxID        sql.NullString  `json:"tax_id"`
	Lat          sql.NullFloat64 `json:"lat"`
	Lng          sql.NullFloat64 `json:"lng"`
}

func (q *Queries) UpdateBuyer(ctx context.Context, arg UpdateBuyerParams) (Buyer, error) {
	row := q.db.QueryRowContext(ctx, updateBuyer,
		arg.BuyerID,
		arg.BuyerCode,
		arg.BuyerName,
		arg.Address,
		arg.PhoneNumber,
		arg.IDCardNumber,
		arg.Email,
		arg.TaxID,
		arg.Lat,
		arg.Lng,
	)
	var i Buyer
	err := row.Scan(
		&i.BuyerID,
		&i.BuyerCode,
		&i.BuyerName,
		&i.Address,
		&i.PhoneNumber,
		&i.IDCardNumber,
		&i.Email,
		&i.TaxID,
		&i.Lat,
		&i.Lng,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateInvoice = `-- name: UpdateInvoice :one
UPDATE invoices
SET
    account_id = $2,
    buyer_id = $3,
    invoice_code = $4,
    total_amount = $5,
    device_holding_id = $6,
    edit_status = $7,
    buyer_name_snapshot = $8,
    address_snapshot = $9,
    phone_number_snapshot = $10,
    tax_id_snapshot = $11,
    id_card_number_snapshot = $12,
    email_snapshot = $13,
    lat_snapshot = $14,
    lng_snapshot = $15,
    updated_at = NOW()
WHERE invoice_id = $1 AND deleted_at IS NULL
RETURNING invoice_id, account_id, buyer_id, invoice_code, total_amount, device_holding_id, edit_status, paid_locked, buyer_name_snapshot, address_snapshot, id_card_number_snapshot, email_snapshot, lat_snapshot, lng_snapshot, phone_number_snapshot, tax_id_snapshot, is_active, created_at, updated_at, deleted_at
`

type UpdateInvoiceParams struct {
	InvoiceID            uuid.UUID       `json:"invoice_id"`
	AccountID            uuid.NullUUID   `json:"account_id"`
	BuyerID              uuid.NullUUID   `json:"buyer_id"`
	InvoiceCode          string          `json:"invoice_code"`
	TotalAmount          int64           `json:"total_amount"`
	DeviceHoldingID      sql.NullString  `json:"device_holding_id"`
	EditStatus           sql.NullBool    `json:"edit_status"`
	BuyerNameSnapshot    sql.NullString  `json:"buyer_name_snapshot"`
	AddressSnapshot      sql.NullString  `json:"address_snapshot"`
	PhoneNumberSnapshot  sql.NullString  `json:"phone_number_snapshot"`
	TaxIDSnapshot        sql.NullString  `json:"tax_id_snapshot"`
	IDCardNumberSnapshot sql.NullString  `json:"id_card_number_snapshot"`
	EmailSnapshot        sql.NullString  `json:"email_snapshot"`
	LatSnapshot          sql.NullFloat64 `json:"lat_snapshot"`
	LngSnapshot          sql.NullFloat64 `json:"lng_snapshot"`
}

func (q *Queries) UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, updateInvoice,
		arg.InvoiceID,
		arg.AccountID,
		arg.BuyerID,
		arg.InvoiceCode,
		arg.TotalAmount,
		arg.DeviceHoldingID,
		arg.EditStatus,
		arg.BuyerNameSnapshot,
		arg.AddressSnapshot,
		arg.PhoneNumberSnapshot,
		arg.TaxIDSnapshot,
		arg.IDCardNumberSnapshot,
		arg.EmailSnapshot,
		arg.LatSnapshot,
		arg.LngSnapshot,
	)
	var i Invoice
	err := row.Scan(
		&i.InvoiceID,
		&i.AccountID,
		&i.BuyerID,
		&i.InvoiceCode,
		&i.TotalAmount,
		&i.DeviceHoldingID,
		&i.EditStatus,
		&i.PaidLocked,
		&i.BuyerNameSnapshot,
		&i.AddressSnapshot,
		&i.IDCardNumberSnapshot,
		&i.EmailSnapshot,
		&i.LatSnapshot,
		&i.LngSnapshot,
		&i.PhoneNumberSnapshot,
		&i.TaxIDSnapshot,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :one
UPDATE invoices
SET 
    device_holding_id = $2,
    edit_status = $3,
    updated_at = NOW()
WHERE invoice_id = $1 AND deleted_at IS NULL
RETURNING invoice_id, account_id, buyer_id, invoice_code, total_amount, device_holding_id, edit_status, paid_locked, buyer_name_snapshot, address_snapshot, id_card_number_snapshot, email_snapshot, lat_snapshot, lng_snapshot, phone_number_snapshot, tax_id_snapshot, is_active, created_at, updated_at, deleted_at
`

type UpdateInvoiceStatusParams struct {
	InvoiceID       uuid.UUID      `json:"invoice_id"`
	DeviceHoldingID sql.NullString `json:"device_holding_id"`
	EditStatus      sql.NullBool   `json:"edit_status"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRowContext(ctx, updateInvoiceStatus, arg.InvoiceID, arg.DeviceHoldingID, arg.EditStatus)
	var i Invoice
	err := row.Scan(
		&i.InvoiceID,
		&i.AccountID,
		&i.BuyerID,
		&i.InvoiceCode,
		&i.TotalAmount,
		&i.DeviceHoldingID,
		&i.EditStatus,
		&i.PaidLocked,
		&i.BuyerNameSnapshot,
		&i.AddressSnapshot,
		&i.IDCardNumberSnapshot,
		&i.EmailSnapshot,
		&i.LatSnapshot,
		&i.LngSnapshot,
		&i.PhoneNumberSnapshot,
		&i.TaxIDSnapshot,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateLineItem = `-- name: UpdateLineItem :one
UPDATE line_items
SET
    item_id = $2,
    unit_id = $3,
    quantity = $4,
    unit_price_custom = $5,
    sub_total = $6,
    item_name_snapshot = $7,
    unit_name_snapshot = $8
WHERE line_item_id = $1
RETURNING line_item_id, invoice_id, item_id, unit_id, quantity, unit_price_custom, sub_total, item_name_snapshot, unit_name_snapshot, position_key, created_at
`

type UpdateLineItemParams struct {
	LineItemID       uuid.UUID      `json:"line_item_id"`
	ItemID           uuid.NullUUID  `json:"item_id"`
	UnitID           uuid.NullUUID  `json:"unit_id"`
	Quantity         int32          `json:"quantity"`
	UnitPriceCustom  sql.NullInt64  `json:"unit_price_custom"`
	SubTotal         int64          `json:"sub_total"`
	ItemNameSnapshot sql.NullString `json:"item_name_snapshot"`
	UnitNameSnapshot sql.NullString `json:"unit_name_snapshot"`
}

func (q *Queries) UpdateLineItem(ctx context.Context, arg UpdateLineItemParams) (LineItem, error) {
	row := q.db.QueryRowContext(ctx, updateLineItem,
		arg.LineItemID,
		arg.ItemID,
		arg.UnitID,
		arg.Quantity,
		arg.UnitPriceCustom,
		arg.SubTotal,
		arg.ItemNameSnapshot,
		arg.UnitNameSnapshot,
	)
	var i LineItem
	err := row.Scan(
		&i.LineItemID,
		&i.InvoiceID,
		&i.ItemID,
		&i.UnitID,
		&i.Quantity,
		&i.UnitPriceCustom,
		&i.SubTotal,
		&i.ItemNameSnapshot,
		&i.UnitNameSnapshot,
		&i.PositionKey,
		&i.CreatedAt,
	)
	return i, err
}

const updateLineItemPos = `-- name: UpdateLineItemPos :exec
UPDATE line_items
SET position_key = $2
WHERE line_item_id = $1
`

type UpdateLineItemPosParams struct {
	LineItemID  uuid.UUID `json:"line_item_id"`
	PositionKey string    `json:"position_key"`
}

func (q *Queries) UpdateLineItemPos(ctx context.Context, arg UpdateLineItemPosParams) error {
	_, err := q.db.ExecContext(ctx, updateLineItemPos, arg.LineItemID, arg.PositionKey)
	return err
}
