// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const assignUnitToItem = `-- name: AssignUnitToItem :one
UPDATE units
SET item_id = $1, updated_at = NOW()
WHERE unit_id = $2
RETURNING unit_id, unit_name, unit_price_default, item_id, is_active, created_at, updated_at, deleted_at
`

type AssignUnitToItemParams struct {
	ItemID uuid.NullUUID `json:"item_id"`
	UnitID uuid.UUID     `json:"unit_id"`
}

func (q *Queries) AssignUnitToItem(ctx context.Context, arg AssignUnitToItemParams) (Unit, error) {
	row := q.db.QueryRowContext(ctx, assignUnitToItem, arg.ItemID, arg.UnitID)
	var i Unit
	err := row.Scan(
		&i.UnitID,
		&i.UnitName,
		&i.UnitPriceDefault,
		&i.ItemID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (
  item_formal_name,
  item_short_names,
  type_id
) VALUES (
  $1,
  $2,
  $3
)
RETURNING item_id, item_formal_name, item_short_names, type_id, is_active, created_at, updated_at, deleted_at
`

type CreateItemParams struct {
	ItemFormalName string                `json:"item_formal_name"`
	ItemShortNames pqtype.NullRawMessage `json:"item_short_names"`
	TypeID         uuid.NullUUID         `json:"type_id"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem, arg.ItemFormalName, arg.ItemShortNames, arg.TypeID)
	var i Item
	err := row.Scan(
		&i.ItemID,
		&i.ItemFormalName,
		&i.ItemShortNames,
		&i.TypeID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createType = `-- name: CreateType :one
INSERT INTO types (
  type_name
) VALUES (
  $1
)
RETURNING type_id, type_name, is_active, created_at, updated_at, deleted_at
`

func (q *Queries) CreateType(ctx context.Context, typeName string) (Type, error) {
	row := q.db.QueryRowContext(ctx, createType, typeName)
	var i Type
	err := row.Scan(
		&i.TypeID,
		&i.TypeName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (
  unit_name,
  unit_price_default,
  item_id
) VALUES (
  $1,
  $2,
  $3
)
RETURNING unit_id, unit_name, unit_price_default, item_id, is_active, created_at, updated_at, deleted_at
`

type CreateUnitParams struct {
	UnitName         string        `json:"unit_name"`
	UnitPriceDefault int64         `json:"unit_price_default"`
	ItemID           uuid.NullUUID `json:"item_id"`
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error) {
	row := q.db.QueryRowContext(ctx, createUnit, arg.UnitName, arg.UnitPriceDefault, arg.ItemID)
	var i Unit
	err := row.Scan(
		&i.UnitID,
		&i.UnitName,
		&i.UnitPriceDefault,
		&i.ItemID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listItems = `-- name: ListItems :many
SELECT item_id, item_formal_name, item_short_names, type_id, is_active, created_at, updated_at, deleted_at FROM items
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemFormalName,
			&i.ItemShortNames,
			&i.TypeID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTypes = `-- name: ListTypes :many
SELECT type_id, type_name, is_active, created_at, updated_at, deleted_at FROM types
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListTypes(ctx context.Context) ([]Type, error) {
	rows, err := q.db.QueryContext(ctx, listTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Type
	for rows.Next() {
		var i Type
		if err := rows.Scan(
			&i.TypeID,
			&i.TypeName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnits = `-- name: ListUnits :many
SELECT unit_id, unit_name, unit_price_default, item_id, is_active, created_at, updated_at, deleted_at FROM units
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListUnits(ctx context.Context) ([]Unit, error) {
	rows, err := q.db.QueryContext(ctx, listUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Unit
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.UnitID,
			&i.UnitName,
			&i.UnitPriceDefault,
			&i.ItemID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchItems = `-- name: SearchItems :many
SELECT item_id, item_formal_name, item_short_names, type_id, is_active, created_at, updated_at, deleted_at FROM items
WHERE deleted_at IS NULL
AND (
  -- ILIKE and trigram similarity can use pg_trgm index on item_formal_name
  item_formal_name ILIKE '%' || $1 || '%'
  OR item_formal_name % $1
  -- Exact short-name match on JSONB array can use GIN index
  OR (my_unaccent(item_short_names::text)) ILIKE '%' || my_unaccent($1) || '%' -- Note: Make JsonB into part treat it as text for index usage
)
ORDER BY
  -- Rank exact formal-name match highest
  CASE WHEN item_formal_name = $1 THEN 0 ELSE 1 END,
  -- Then prefix match
  CASE WHEN item_formal_name ILIKE $1 || '%' THEN 0 ELSE 1 END,
  -- Then exact short-name match
  CASE WHEN (my_unaccent(item_short_names::text)) ILIKE '%' || my_unaccent($1) || '%' THEN 0 ELSE 1 END,
  -- Then fuzzy relevance for remaining formal-name matches
  similarity(item_formal_name, $1) DESC,
  created_at DESC
LIMIT $2
`

type SearchItemsParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int32          `json:"limit"`
}

func (q *Queries) SearchItems(ctx context.Context, arg SearchItemsParams) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, searchItems, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemFormalName,
			&i.ItemShortNames,
			&i.TypeID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
