// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const assignUnitToItem = `-- name: AssignUnitToItem :one
UPDATE units
SET item_id = $1, updated_at = NOW()
WHERE unit_id = $2
RETURNING unit_id, unit_name, unit_price_default, item_id, ratio, is_base_unit, is_active, created_at, updated_at, deleted_at
`

type AssignUnitToItemParams struct {
	ItemID uuid.NullUUID `json:"item_id"`
	UnitID uuid.UUID     `json:"unit_id"`
}

func (q *Queries) AssignUnitToItem(ctx context.Context, arg AssignUnitToItemParams) (Unit, error) {
	row := q.db.QueryRowContext(ctx, assignUnitToItem, arg.ItemID, arg.UnitID)
	var i Unit
	err := row.Scan(
		&i.UnitID,
		&i.UnitName,
		&i.UnitPriceDefault,
		&i.ItemID,
		&i.Ratio,
		&i.IsBaseUnit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createItem = `-- name: CreateItem :one
INSERT INTO items (
  item_default_name,
  type_id
) VALUES (
  $1,
  $2
)
RETURNING item_id, item_default_name, type_id, is_active, created_at, updated_at, deleted_at
`

type CreateItemParams struct {
	ItemDefaultName string        `json:"item_default_name"`
	TypeID          uuid.NullUUID `json:"type_id"`
}

func (q *Queries) CreateItem(ctx context.Context, arg CreateItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, createItem, arg.ItemDefaultName, arg.TypeID)
	var i Item
	err := row.Scan(
		&i.ItemID,
		&i.ItemDefaultName,
		&i.TypeID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createItemOtherName = `-- name: CreateItemOtherName :one
INSERT INTO item_other_names (
  item_id,
  name_string
) VALUES (
  $1, $2
)
RETURNING item_other_name_id, item_id, name_string
`

type CreateItemOtherNameParams struct {
	ItemID     uuid.UUID `json:"item_id"`
	NameString string    `json:"name_string"`
}

func (q *Queries) CreateItemOtherName(ctx context.Context, arg CreateItemOtherNameParams) (ItemOtherName, error) {
	row := q.db.QueryRowContext(ctx, createItemOtherName, arg.ItemID, arg.NameString)
	var i ItemOtherName
	err := row.Scan(&i.ItemOtherNameID, &i.ItemID, &i.NameString)
	return i, err
}

const createType = `-- name: CreateType :one
INSERT INTO types (
  type_name
) VALUES (
  $1
)
RETURNING type_id, type_name, is_active, created_at, updated_at, deleted_at
`

func (q *Queries) CreateType(ctx context.Context, typeName string) (Type, error) {
	row := q.db.QueryRowContext(ctx, createType, typeName)
	var i Type
	err := row.Scan(
		&i.TypeID,
		&i.TypeName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (
  unit_name,
  unit_price_default,
  item_id,
  ratio,
  is_base_unit
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING unit_id, unit_name, unit_price_default, item_id, ratio, is_base_unit, is_active, created_at, updated_at, deleted_at
`

type CreateUnitParams struct {
	UnitName         string        `json:"unit_name"`
	UnitPriceDefault int64         `json:"unit_price_default"`
	ItemID           uuid.NullUUID `json:"item_id"`
	Ratio            int64         `json:"ratio"`
	IsBaseUnit       bool          `json:"is_base_unit"`
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error) {
	row := q.db.QueryRowContext(ctx, createUnit,
		arg.UnitName,
		arg.UnitPriceDefault,
		arg.ItemID,
		arg.Ratio,
		arg.IsBaseUnit,
	)
	var i Unit
	err := row.Scan(
		&i.UnitID,
		&i.UnitName,
		&i.UnitPriceDefault,
		&i.ItemID,
		&i.Ratio,
		&i.IsBaseUnit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteItem = `-- name: DeleteItem :exec
UPDATE items
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE item_id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, itemID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteItem, itemID)
	return err
}

const deleteItemOtherName = `-- name: DeleteItemOtherName :exec
DELETE FROM item_other_names
WHERE item_other_name_id = $1
`

func (q *Queries) DeleteItemOtherName(ctx context.Context, itemOtherNameID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteItemOtherName, itemOtherNameID)
	return err
}

const deleteUnit = `-- name: DeleteUnit :exec
UPDATE units
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE unit_id = $1
`

func (q *Queries) DeleteUnit(ctx context.Context, unitID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUnit, unitID)
	return err
}

const getItemByID = `-- name: GetItemByID :one
SELECT i.item_id, i.item_default_name, i.type_id, i.is_active, i.created_at, i.updated_at, i.deleted_at,
       COALESCE(JSON_AGG(DISTINCT JSONB_BUILD_OBJECT(
         'item_other_name_id', ion.item_other_name_id,
         'name_string', ion.name_string
       )) FILTER (WHERE ion.item_other_name_id IS NOT NULL), '[]')::JSONB AS item_other_names,
       COALESCE(JSON_AGG(DISTINCT JSONB_BUILD_OBJECT(
         'unit_id', u.unit_id,
         'unit_name', u.unit_name,
         'unit_price_default', u.unit_price_default,
         'ratio', u.ratio,
         'is_base_unit', u.is_base_unit
       )) FILTER (WHERE u.unit_id IS NOT NULL), '[]')::JSONB AS units
FROM items i
LEFT JOIN item_other_names ion ON i.item_id = ion.item_id
LEFT JOIN units u ON i.item_id = u.item_id AND u.deleted_at IS NULL
WHERE i.item_id = $1 AND i.deleted_at IS NULL
GROUP BY i.item_id
`

type GetItemByIDRow struct {
	ItemID          uuid.UUID       `json:"item_id"`
	ItemDefaultName string          `json:"item_default_name"`
	TypeID          uuid.NullUUID   `json:"type_id"`
	IsActive        sql.NullBool    `json:"is_active"`
	CreatedAt       sql.NullTime    `json:"created_at"`
	UpdatedAt       sql.NullTime    `json:"updated_at"`
	DeletedAt       sql.NullTime    `json:"deleted_at"`
	ItemOtherNames  json.RawMessage `json:"item_other_names"`
	Units           json.RawMessage `json:"units"`
}

func (q *Queries) GetItemByID(ctx context.Context, itemID uuid.UUID) (GetItemByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, itemID)
	var i GetItemByIDRow
	err := row.Scan(
		&i.ItemID,
		&i.ItemDefaultName,
		&i.TypeID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ItemOtherNames,
		&i.Units,
	)
	return i, err
}

const getUnitByID = `-- name: GetUnitByID :one
SELECT unit_id, unit_name, unit_price_default, item_id, ratio, is_base_unit, is_active, created_at, updated_at, deleted_at FROM units
WHERE unit_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUnitByID(ctx context.Context, unitID uuid.UUID) (Unit, error) {
	row := q.db.QueryRowContext(ctx, getUnitByID, unitID)
	var i Unit
	err := row.Scan(
		&i.UnitID,
		&i.UnitName,
		&i.UnitPriceDefault,
		&i.ItemID,
		&i.Ratio,
		&i.IsBaseUnit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDeletedItems = `-- name: ListDeletedItems :many
SELECT i.item_id, i.item_default_name, i.type_id, i.is_active, i.created_at, i.updated_at, i.deleted_at, 
       COALESCE(JSON_AGG(DISTINCT JSONB_BUILD_OBJECT(
         'item_other_name_id', ion.item_other_name_id,
         'name_string', ion.name_string
       )) FILTER (WHERE ion.item_other_name_id IS NOT NULL), '[]')::JSONB AS item_other_names,
       COALESCE(JSON_AGG(DISTINCT JSONB_BUILD_OBJECT(
         'unit_id', u.unit_id,
         'unit_name', u.unit_name,
         'unit_price_default', u.unit_price_default,
         'ratio', u.ratio,
         'is_base_unit', u.is_base_unit
       )) FILTER (WHERE u.unit_id IS NOT NULL), '[]')::JSONB AS units
FROM items i
LEFT JOIN item_other_names ion ON i.item_id = ion.item_id
LEFT JOIN units u ON i.item_id = u.item_id AND u.deleted_at IS NULL
WHERE i.deleted_at IS NOT NULL
GROUP BY i.item_id
ORDER BY i.deleted_at DESC
`

type ListDeletedItemsRow struct {
	ItemID          uuid.UUID       `json:"item_id"`
	ItemDefaultName string          `json:"item_default_name"`
	TypeID          uuid.NullUUID   `json:"type_id"`
	IsActive        sql.NullBool    `json:"is_active"`
	CreatedAt       sql.NullTime    `json:"created_at"`
	UpdatedAt       sql.NullTime    `json:"updated_at"`
	DeletedAt       sql.NullTime    `json:"deleted_at"`
	ItemOtherNames  json.RawMessage `json:"item_other_names"`
	Units           json.RawMessage `json:"units"`
}

func (q *Queries) ListDeletedItems(ctx context.Context) ([]ListDeletedItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeletedItemsRow
	for rows.Next() {
		var i ListDeletedItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemDefaultName,
			&i.TypeID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ItemOtherNames,
			&i.Units,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemOtherNames = `-- name: ListItemOtherNames :many
SELECT item_other_name_id, item_id, name_string FROM item_other_names
WHERE item_id = $1
`

func (q *Queries) ListItemOtherNames(ctx context.Context, itemID uuid.UUID) ([]ItemOtherName, error) {
	rows, err := q.db.QueryContext(ctx, listItemOtherNames, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemOtherName
	for rows.Next() {
		var i ItemOtherName
		if err := rows.Scan(&i.ItemOtherNameID, &i.ItemID, &i.NameString); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT i.item_id, i.item_default_name, i.type_id, i.is_active, i.created_at, i.updated_at, i.deleted_at, 
       COALESCE(JSON_AGG(DISTINCT JSONB_BUILD_OBJECT(
         'item_other_name_id', ion.item_other_name_id,
         'name_string', ion.name_string
       )) FILTER (WHERE ion.item_other_name_id IS NOT NULL), '[]')::JSONB AS item_other_names,
       COALESCE(JSON_AGG(DISTINCT JSONB_BUILD_OBJECT(
         'unit_id', u.unit_id,
         'unit_name', u.unit_name,
         'unit_price_default', u.unit_price_default,
         'ratio', u.ratio,
         'is_base_unit', u.is_base_unit
       )) FILTER (WHERE u.unit_id IS NOT NULL), '[]')::JSONB AS units
FROM items i
LEFT JOIN item_other_names ion ON i.item_id = ion.item_id
LEFT JOIN units u ON i.item_id = u.item_id AND u.deleted_at IS NULL
WHERE i.deleted_at IS NULL
GROUP BY i.item_id
ORDER BY i.created_at DESC
`

type ListItemsRow struct {
	ItemID          uuid.UUID       `json:"item_id"`
	ItemDefaultName string          `json:"item_default_name"`
	TypeID          uuid.NullUUID   `json:"type_id"`
	IsActive        sql.NullBool    `json:"is_active"`
	CreatedAt       sql.NullTime    `json:"created_at"`
	UpdatedAt       sql.NullTime    `json:"updated_at"`
	DeletedAt       sql.NullTime    `json:"deleted_at"`
	ItemOtherNames  json.RawMessage `json:"item_other_names"`
	Units           json.RawMessage `json:"units"`
}

func (q *Queries) ListItems(ctx context.Context) ([]ListItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsRow
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemDefaultName,
			&i.TypeID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ItemOtherNames,
			&i.Units,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemsFiltered = `-- name: ListItemsFiltered :many
SELECT i.item_id, i.item_default_name, i.type_id, i.is_active, i.created_at, i.updated_at, i.deleted_at, 
       COALESCE(JSON_AGG(DISTINCT JSONB_BUILD_OBJECT(
         'item_other_name_id', ion.item_other_name_id,
         'name_string', ion.name_string
       )) FILTER (WHERE ion.item_other_name_id IS NOT NULL), '[]')::JSONB AS item_other_names,
       COALESCE(JSON_AGG(DISTINCT JSONB_BUILD_OBJECT(
         'unit_id', u.unit_id,
         'unit_name', u.unit_name,
         'unit_price_default', u.unit_price_default,
         'ratio', u.ratio,
         'is_base_unit', u.is_base_unit
       )) FILTER (WHERE u.unit_id IS NOT NULL), '[]')::JSONB AS units
FROM items i
LEFT JOIN item_other_names ion ON i.item_id = ion.item_id
LEFT JOIN units u ON i.item_id = u.item_id AND u.deleted_at IS NULL
WHERE i.deleted_at IS NULL
AND ($1::UUID IS NULL OR i.type_id = $1::UUID)
GROUP BY i.item_id
ORDER BY 
  CASE WHEN $2::text = 'item_default_name' AND $3::text = 'asc' THEN i.item_default_name END ASC,
  CASE WHEN $2::text = 'item_default_name' AND $3::text = 'desc' THEN i.item_default_name END DESC,
  i.created_at DESC
LIMIT $5
OFFSET $4
`

type ListItemsFilteredParams struct {
	TypeID    uuid.NullUUID `json:"type_id"`
	SortBy    string        `json:"sort_by"`
	SortOrder string        `json:"sort_order"`
	OffsetVal int32         `json:"offset_val"`
	LimitVal  int32         `json:"limit_val"`
}

type ListItemsFilteredRow struct {
	ItemID          uuid.UUID       `json:"item_id"`
	ItemDefaultName string          `json:"item_default_name"`
	TypeID          uuid.NullUUID   `json:"type_id"`
	IsActive        sql.NullBool    `json:"is_active"`
	CreatedAt       sql.NullTime    `json:"created_at"`
	UpdatedAt       sql.NullTime    `json:"updated_at"`
	DeletedAt       sql.NullTime    `json:"deleted_at"`
	ItemOtherNames  json.RawMessage `json:"item_other_names"`
	Units           json.RawMessage `json:"units"`
}

func (q *Queries) ListItemsFiltered(ctx context.Context, arg ListItemsFilteredParams) ([]ListItemsFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemsFiltered,
		arg.TypeID,
		arg.SortBy,
		arg.SortOrder,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsFilteredRow
	for rows.Next() {
		var i ListItemsFilteredRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemDefaultName,
			&i.TypeID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ItemOtherNames,
			&i.Units,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTypes = `-- name: ListTypes :many
SELECT type_id, type_name, is_active, created_at, updated_at, deleted_at FROM types
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListTypes(ctx context.Context) ([]Type, error) {
	rows, err := q.db.QueryContext(ctx, listTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Type
	for rows.Next() {
		var i Type
		if err := rows.Scan(
			&i.TypeID,
			&i.TypeName,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnits = `-- name: ListUnits :many
SELECT unit_id, unit_name, unit_price_default, item_id, ratio, is_base_unit, is_active, created_at, updated_at, deleted_at FROM units
WHERE deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListUnits(ctx context.Context) ([]Unit, error) {
	rows, err := q.db.QueryContext(ctx, listUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Unit
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.UnitID,
			&i.UnitName,
			&i.UnitPriceDefault,
			&i.ItemID,
			&i.Ratio,
			&i.IsBaseUnit,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchItem = `-- name: PatchItem :one
UPDATE items
SET
  item_default_name = CASE
    WHEN $1::boolean THEN $2
    ELSE item_default_name
  END,
  type_id = CASE
    WHEN $3::boolean THEN $4
    ELSE type_id
  END,
  updated_at = NOW()
WHERE item_id = $5
AND deleted_at IS NULL
RETURNING item_id, item_default_name, type_id, is_active, created_at, updated_at, deleted_at
`

type PatchItemParams struct {
	SetItemDefaultName bool          `json:"set_item_default_name"`
	ItemDefaultName    string        `json:"item_default_name"`
	SetTypeID          bool          `json:"set_type_id"`
	TypeID             uuid.NullUUID `json:"type_id"`
	ItemID             uuid.UUID     `json:"item_id"`
}

func (q *Queries) PatchItem(ctx context.Context, arg PatchItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, patchItem,
		arg.SetItemDefaultName,
		arg.ItemDefaultName,
		arg.SetTypeID,
		arg.TypeID,
		arg.ItemID,
	)
	var i Item
	err := row.Scan(
		&i.ItemID,
		&i.ItemDefaultName,
		&i.TypeID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const patchType = `-- name: PatchType :one
UPDATE types
SET
  type_name = CASE
    WHEN $1::boolean THEN $2
    ELSE type_name
  END,
  updated_at = NOW()
WHERE type_id = $3
AND deleted_at IS NULL
RETURNING type_id, type_name, is_active, created_at, updated_at, deleted_at
`

type PatchTypeParams struct {
	SetTypeName bool      `json:"set_type_name"`
	TypeName    string    `json:"type_name"`
	TypeID      uuid.UUID `json:"type_id"`
}

func (q *Queries) PatchType(ctx context.Context, arg PatchTypeParams) (Type, error) {
	row := q.db.QueryRowContext(ctx, patchType, arg.SetTypeName, arg.TypeName, arg.TypeID)
	var i Type
	err := row.Scan(
		&i.TypeID,
		&i.TypeName,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const patchUnit = `-- name: PatchUnit :one
UPDATE units
SET
  unit_name = CASE
    WHEN $1::boolean THEN $2
    ELSE unit_name
  END,
  unit_price_default = CASE
    WHEN $3::boolean THEN $4
    ELSE unit_price_default
  END,
  item_id = CASE
    WHEN $5::boolean THEN $6
    ELSE item_id
  END,
  ratio = CASE
    WHEN $7::boolean THEN $8
    ELSE ratio
  END,
  is_base_unit = CASE
    WHEN $9::boolean THEN $10
    ELSE is_base_unit
  END,
  updated_at = NOW()
WHERE unit_id = $11
AND deleted_at IS NULL
RETURNING unit_id, unit_name, unit_price_default, item_id, ratio, is_base_unit, is_active, created_at, updated_at, deleted_at
`

type PatchUnitParams struct {
	SetUnitName         bool          `json:"set_unit_name"`
	UnitName            string        `json:"unit_name"`
	SetUnitPriceDefault bool          `json:"set_unit_price_default"`
	UnitPriceDefault    int64         `json:"unit_price_default"`
	SetItemID           bool          `json:"set_item_id"`
	ItemID              uuid.NullUUID `json:"item_id"`
	SetRatio            bool          `json:"set_ratio"`
	Ratio               int64         `json:"ratio"`
	SetIsBaseUnit       bool          `json:"set_is_base_unit"`
	IsBaseUnit          bool          `json:"is_base_unit"`
	UnitID              uuid.UUID     `json:"unit_id"`
}

func (q *Queries) PatchUnit(ctx context.Context, arg PatchUnitParams) (Unit, error) {
	row := q.db.QueryRowContext(ctx, patchUnit,
		arg.SetUnitName,
		arg.UnitName,
		arg.SetUnitPriceDefault,
		arg.UnitPriceDefault,
		arg.SetItemID,
		arg.ItemID,
		arg.SetRatio,
		arg.Ratio,
		arg.SetIsBaseUnit,
		arg.IsBaseUnit,
		arg.UnitID,
	)
	var i Unit
	err := row.Scan(
		&i.UnitID,
		&i.UnitName,
		&i.UnitPriceDefault,
		&i.ItemID,
		&i.Ratio,
		&i.IsBaseUnit,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const restoreItem = `-- name: RestoreItem :exec
UPDATE items
SET deleted_at = NULL,
    updated_at = NOW()
WHERE item_id = $1
`

func (q *Queries) RestoreItem(ctx context.Context, itemID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, restoreItem, itemID)
	return err
}

const searchItems = `-- name: SearchItems :many
SELECT i.item_id, i.item_default_name, i.type_id, i.is_active, i.created_at, i.updated_at, i.deleted_at,
       COALESCE(JSON_AGG(DISTINCT JSONB_BUILD_OBJECT(
         'item_other_name_id', ion.item_other_name_id,
         'name_string', ion.name_string
       )) FILTER (WHERE ion.item_other_name_id IS NOT NULL), '[]')::JSONB AS item_other_names,
       COALESCE(JSON_AGG(DISTINCT JSONB_BUILD_OBJECT(
         'unit_id', u.unit_id,
         'unit_name', u.unit_name,
         'unit_price_default', u.unit_price_default,
         'ratio', u.ratio,
         'is_base_unit', u.is_base_unit
       )) FILTER (WHERE u.unit_id IS NOT NULL), '[]')::JSONB AS units
FROM items i
LEFT JOIN item_other_names ion ON i.item_id = ion.item_id
LEFT JOIN units u ON i.item_id = u.item_id AND u.deleted_at IS NULL
WHERE i.deleted_at IS NULL
AND ($1::UUID IS NULL OR i.type_id = $1::UUID)
AND (
  -- ILIKE and trigram similarity can use pg_trgm index on item_default_name
  my_unaccent(i.item_default_name) ILIKE '%' || my_unaccent($2) || '%'
  OR my_unaccent(i.item_default_name) % my_unaccent($2)
  -- Exact search on other names
  OR EXISTS (
    SELECT 1 FROM item_other_names ion2 
    WHERE ion2.item_id = i.item_id 
    AND my_unaccent(ion2.name_string) ILIKE '%' || my_unaccent($2) || '%'
  )
)
GROUP BY i.item_id
ORDER BY
  -- Rank exact default-name match highest
  CASE WHEN my_unaccent(i.item_default_name) = my_unaccent($2) THEN 0 ELSE 1 END,
  -- Then prefix match
  CASE WHEN my_unaccent(i.item_default_name) ILIKE my_unaccent($2) || '%' THEN 0 ELSE 1 END,
  -- Then fuzzy relevance for remaining default-name matches
  similarity(my_unaccent(i.item_default_name), my_unaccent($2)) DESC,
  i.created_at DESC
LIMIT $3
`

type SearchItemsParams struct {
	TypeID   uuid.NullUUID `json:"type_id"`
	Keyword  string        `json:"keyword"`
	LimitVal int32         `json:"limit_val"`
}

type SearchItemsRow struct {
	ItemID          uuid.UUID       `json:"item_id"`
	ItemDefaultName string          `json:"item_default_name"`
	TypeID          uuid.NullUUID   `json:"type_id"`
	IsActive        sql.NullBool    `json:"is_active"`
	CreatedAt       sql.NullTime    `json:"created_at"`
	UpdatedAt       sql.NullTime    `json:"updated_at"`
	DeletedAt       sql.NullTime    `json:"deleted_at"`
	ItemOtherNames  json.RawMessage `json:"item_other_names"`
	Units           json.RawMessage `json:"units"`
}

func (q *Queries) SearchItems(ctx context.Context, arg SearchItemsParams) ([]SearchItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchItems, arg.TypeID, arg.Keyword, arg.LimitVal)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchItemsRow
	for rows.Next() {
		var i SearchItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ItemDefaultName,
			&i.TypeID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ItemOtherNames,
			&i.Units,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
