// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

type Account struct {
	AccountID uuid.UUID    `json:"account_id"`
	Username  string       `json:"username"`
	Password  string       `json:"password"`
	Name      string       `json:"name"`
	IsActive  sql.NullBool `json:"is_active"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Buyer struct {
	BuyerID      uuid.UUID       `json:"buyer_id"`
	BuyerCode    string          `json:"buyer_code"`
	BuyerName    string          `json:"buyer_name"`
	Address      sql.NullString  `json:"address"`
	PhoneNumber  sql.NullString  `json:"phone_number"`
	IDCardNumber sql.NullString  `json:"id_card_number"`
	Email        sql.NullString  `json:"email"`
	TaxID        sql.NullString  `json:"tax_id"`
	Lat          sql.NullFloat64 `json:"lat"`
	Lng          sql.NullFloat64 `json:"lng"`
	IsActive     sql.NullBool    `json:"is_active"`
	CreatedAt    sql.NullTime    `json:"created_at"`
	UpdatedAt    sql.NullTime    `json:"updated_at"`
	DeletedAt    sql.NullTime    `json:"deleted_at"`
}

type CustomerItemPrice struct {
	CustomerItemPriceID uuid.UUID     `json:"customer_item_price_id"`
	CustomerPriceListID uuid.NullUUID `json:"customer_price_list_id"`
	ItemID              uuid.NullUUID `json:"item_id"`
	UnitID              uuid.NullUUID `json:"unit_id"`
	UnitPriceCustom     int64         `json:"unit_price_custom"`
	PositionKey         string        `json:"position_key"`
	CreatedAt           sql.NullTime  `json:"created_at"`
}

type CustomerPriceList struct {
	CustomerPriceListID uuid.UUID     `json:"customer_price_list_id"`
	Description         string        `json:"description"`
	BuyerID             uuid.NullUUID `json:"buyer_id"`
	IsActive            sql.NullBool  `json:"is_active"`
	CreatedAt           sql.NullTime  `json:"created_at"`
	UpdatedAt           sql.NullTime  `json:"updated_at"`
	DeletedAt           sql.NullTime  `json:"deleted_at"`
}

type Device struct {
	DeviceHoldingID string         `json:"device_holding_id"`
	DeviceName      sql.NullString `json:"device_name"`
}

type GlobalSetting struct {
	ID                 uuid.UUID       `json:"id"`
	GlobalSettingsFile json.RawMessage `json:"global_settings_file"`
	IsSingleton        sql.NullBool    `json:"is_singleton"`
}

type Invoice struct {
	InvoiceID            uuid.UUID       `json:"invoice_id"`
	AccountID            uuid.NullUUID   `json:"account_id"`
	BuyerID              uuid.NullUUID   `json:"buyer_id"`
	InvoiceCode          string          `json:"invoice_code"`
	TotalAmount          int64           `json:"total_amount"`
	DeviceHoldingID      sql.NullString  `json:"device_holding_id"`
	EditStatus           sql.NullBool    `json:"edit_status"`
	PaidLocked           sql.NullBool    `json:"paid_locked"`
	BuyerNameSnapshot    sql.NullString  `json:"buyer_name_snapshot"`
	AddressSnapshot      sql.NullString  `json:"address_snapshot"`
	IDCardNumberSnapshot sql.NullString  `json:"id_card_number_snapshot"`
	EmailSnapshot        sql.NullString  `json:"email_snapshot"`
	LatSnapshot          sql.NullFloat64 `json:"lat_snapshot"`
	LngSnapshot          sql.NullFloat64 `json:"lng_snapshot"`
	PhoneNumberSnapshot  sql.NullString  `json:"phone_number_snapshot"`
	TaxIDSnapshot        sql.NullString  `json:"tax_id_snapshot"`
	IsActive             sql.NullBool    `json:"is_active"`
	CreatedAt            sql.NullTime    `json:"created_at"`
	UpdatedAt            sql.NullTime    `json:"updated_at"`
	DeletedAt            sql.NullTime    `json:"deleted_at"`
}

type Item struct {
	ItemID          uuid.UUID     `json:"item_id"`
	ItemDefaultName string        `json:"item_default_name"`
	TypeID          uuid.NullUUID `json:"type_id"`
	IsActive        sql.NullBool  `json:"is_active"`
	CreatedAt       sql.NullTime  `json:"created_at"`
	UpdatedAt       sql.NullTime  `json:"updated_at"`
	DeletedAt       sql.NullTime  `json:"deleted_at"`
}

type ItemOtherName struct {
	ItemOtherNameID uuid.UUID `json:"item_other_name_id"`
	ItemID          uuid.UUID `json:"item_id"`
	NameString      string    `json:"name_string"`
}

type LineItem struct {
	LineItemID       uuid.UUID      `json:"line_item_id"`
	InvoiceID        uuid.NullUUID  `json:"invoice_id"`
	ItemID           uuid.NullUUID  `json:"item_id"`
	UnitID           uuid.NullUUID  `json:"unit_id"`
	Quantity         int32          `json:"quantity"`
	UnitPriceCustom  sql.NullInt64  `json:"unit_price_custom"`
	SubTotal         int64          `json:"sub_total"`
	ItemNameSnapshot sql.NullString `json:"item_name_snapshot"`
	UnitNameSnapshot sql.NullString `json:"unit_name_snapshot"`
	PositionKey      string         `json:"position_key"`
	CreatedAt        sql.NullTime   `json:"created_at"`
}

type PrintQueue struct {
	PrintJobID          uuid.UUID     `json:"print_job_id"`
	InvoiceID           uuid.NullUUID `json:"invoice_id"`
	CustomerPriceListID uuid.NullUUID `json:"customer_price_list_id"`
	PrintStatus         interface{}   `json:"print_status"`
	PrintType           interface{}   `json:"print_type"`
	PrintPart           interface{}   `json:"print_part"`
	RetryCount          sql.NullInt32 `json:"retry_count"`
	PriorityNum         sql.NullInt32 `json:"priority_num"`
	CreatedAt           sql.NullTime  `json:"created_at"`
	PrintedAt           sql.NullTime  `json:"printed_at"`
	StartedPrintingAt   sql.NullTime  `json:"started_printing_at"`
}

type Type struct {
	TypeID    uuid.UUID    `json:"type_id"`
	TypeName  string       `json:"type_name"`
	IsActive  sql.NullBool `json:"is_active"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Unit struct {
	UnitID           uuid.UUID     `json:"unit_id"`
	UnitName         string        `json:"unit_name"`
	UnitPriceDefault int64         `json:"unit_price_default"`
	ItemID           uuid.NullUUID `json:"item_id"`
	Ratio            int64         `json:"ratio"`
	IsBaseUnit       bool          `json:"is_base_unit"`
	IsActive         sql.NullBool  `json:"is_active"`
	CreatedAt        sql.NullTime  `json:"created_at"`
	UpdatedAt        sql.NullTime  `json:"updated_at"`
	DeletedAt        sql.NullTime  `json:"deleted_at"`
}
