// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type PrintStatusEnum string

const (
	PrintStatusEnumPending   PrintStatusEnum = "Pending"
	PrintStatusEnumPrinting  PrintStatusEnum = "Printing"
	PrintStatusEnumCompleted PrintStatusEnum = "Completed"
	PrintStatusEnumFailed    PrintStatusEnum = "Failed"
)

func (e *PrintStatusEnum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrintStatusEnum(s)
	case string:
		*e = PrintStatusEnum(s)
	default:
		return fmt.Errorf("unsupported scan type for PrintStatusEnum: %T", src)
	}
	return nil
}

type NullPrintStatusEnum struct {
	PrintStatusEnum PrintStatusEnum `json:"print_status_enum"`
	Valid           bool            `json:"valid"` // Valid is true if PrintStatusEnum is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrintStatusEnum) Scan(value interface{}) error {
	if value == nil {
		ns.PrintStatusEnum, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrintStatusEnum.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrintStatusEnum) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrintStatusEnum), nil
}

type Account struct {
	AccountID uuid.UUID    `json:"account_id"`
	Username  string       `json:"username"`
	Password  string       `json:"password"`
	Name      string       `json:"name"`
	IsActive  sql.NullBool `json:"is_active"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Buyer struct {
	BuyerID      uuid.UUID      `json:"buyer_id"`
	BuyerCode    string         `json:"buyer_code"`
	BuyerName    string         `json:"buyer_name"`
	Address      sql.NullString `json:"address"`
	PhoneNumber  sql.NullString `json:"phone_number"`
	IDCardNumber sql.NullString `json:"id_card_number"`
	IsActive     sql.NullBool   `json:"is_active"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
	DeletedAt    sql.NullTime   `json:"deleted_at"`
}

type Invoice struct {
	InvoiceID           uuid.UUID      `json:"invoice_id"`
	AccountID           uuid.NullUUID  `json:"account_id"`
	BuyerID             uuid.NullUUID  `json:"buyer_id"`
	InvoiceCode         string         `json:"invoice_code"`
	TotalAmount         int64          `json:"total_amount"`
	DeviceHoldingID     sql.NullString `json:"device_holding_id"`
	EditStatus          sql.NullBool   `json:"edit_status"`
	BuyerNameSnapshot   sql.NullString `json:"buyer_name_snapshot"`
	AddressSnapshot     sql.NullString `json:"address_snapshot"`
	PhoneNumberSnapshot sql.NullString `json:"phone_number_snapshot"`
	IsActive            sql.NullBool   `json:"is_active"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
}

type Item struct {
	ItemID         uuid.UUID             `json:"item_id"`
	ItemFormalName string                `json:"item_formal_name"`
	ItemShortNames pqtype.NullRawMessage `json:"item_short_names"`
	TypeID         uuid.NullUUID         `json:"type_id"`
	IsActive       sql.NullBool          `json:"is_active"`
	CreatedAt      sql.NullTime          `json:"created_at"`
	UpdatedAt      sql.NullTime          `json:"updated_at"`
	DeletedAt      sql.NullTime          `json:"deleted_at"`
}

type LineItem struct {
	LineItemID       uuid.UUID      `json:"line_item_id"`
	InvoiceID        uuid.NullUUID  `json:"invoice_id"`
	ItemID           uuid.NullUUID  `json:"item_id"`
	UnitID           uuid.NullUUID  `json:"unit_id"`
	Quantity         int32          `json:"quantity"`
	UnitPriceCustom  sql.NullInt64  `json:"unit_price_custom"`
	SubTotal         int64          `json:"sub_total"`
	ItemNameSnapshot sql.NullString `json:"item_name_snapshot"`
	UnitNameSnapshot sql.NullString `json:"unit_name_snapshot"`
}

type PrintQueue struct {
	PrintJobID  uuid.UUID           `json:"print_job_id"`
	InvoiceID   uuid.NullUUID       `json:"invoice_id"`
	PrintStatus NullPrintStatusEnum `json:"print_status"`
	RetryCount  sql.NullInt32       `json:"retry_count"`
	PriorityNum sql.NullInt32       `json:"priority_num"`
	CreatedAt   sql.NullTime        `json:"created_at"`
	PrintedAt   sql.NullTime        `json:"printed_at"`
}

type Type struct {
	TypeID    uuid.UUID    `json:"type_id"`
	TypeName  string       `json:"type_name"`
	IsActive  sql.NullBool `json:"is_active"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

type Unit struct {
	UnitID           uuid.UUID     `json:"unit_id"`
	UnitName         string        `json:"unit_name"`
	UnitPriceDefault int64         `json:"unit_price_default"`
	ItemID           uuid.NullUUID `json:"item_id"`
	IsActive         sql.NullBool  `json:"is_active"`
	CreatedAt        sql.NullTime  `json:"created_at"`
	UpdatedAt        sql.NullTime  `json:"updated_at"`
	DeletedAt        sql.NullTime  `json:"deleted_at"`
}
