// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pricelist.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
)

const createCustomerItemPrice = `-- name: CreateCustomerItemPrice :one
INSERT INTO customer_item_prices (
    customer_price_list_id,
    item_id,
    unit_id,
    unit_price_custom,
    position_key
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING customer_item_price_id, customer_price_list_id, item_id, unit_id, unit_price_custom, position_key, created_at
`

type CreateCustomerItemPriceParams struct {
	CustomerPriceListID uuid.NullUUID `json:"customer_price_list_id"`
	ItemID              uuid.NullUUID `json:"item_id"`
	UnitID              uuid.NullUUID `json:"unit_id"`
	UnitPriceCustom     int64         `json:"unit_price_custom"`
	PositionKey         string        `json:"position_key"`
}

func (q *Queries) CreateCustomerItemPrice(ctx context.Context, arg CreateCustomerItemPriceParams) (CustomerItemPrice, error) {
	row := q.db.QueryRowContext(ctx, createCustomerItemPrice,
		arg.CustomerPriceListID,
		arg.ItemID,
		arg.UnitID,
		arg.UnitPriceCustom,
		arg.PositionKey,
	)
	var i CustomerItemPrice
	err := row.Scan(
		&i.CustomerItemPriceID,
		&i.CustomerPriceListID,
		&i.ItemID,
		&i.UnitID,
		&i.UnitPriceCustom,
		&i.PositionKey,
		&i.CreatedAt,
	)
	return i, err
}

const createCustomerPriceList = `-- name: CreateCustomerPriceList :one
INSERT INTO customer_price_lists (
    description,
    buyer_id
) VALUES (
    $1, $2
) RETURNING customer_price_list_id, description, buyer_id, is_active, created_at, updated_at, deleted_at
`

type CreateCustomerPriceListParams struct {
	Description string        `json:"description"`
	BuyerID     uuid.NullUUID `json:"buyer_id"`
}

func (q *Queries) CreateCustomerPriceList(ctx context.Context, arg CreateCustomerPriceListParams) (CustomerPriceList, error) {
	row := q.db.QueryRowContext(ctx, createCustomerPriceList, arg.Description, arg.BuyerID)
	var i CustomerPriceList
	err := row.Scan(
		&i.CustomerPriceListID,
		&i.Description,
		&i.BuyerID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCustomerItemPricesByPriceListID = `-- name: DeleteCustomerItemPricesByPriceListID :exec
DELETE FROM customer_item_prices
WHERE customer_price_list_id = $1
`

func (q *Queries) DeleteCustomerItemPricesByPriceListID(ctx context.Context, customerPriceListID uuid.NullUUID) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerItemPricesByPriceListID, customerPriceListID)
	return err
}

const deleteCustomerPriceList = `-- name: DeleteCustomerPriceList :exec
UPDATE customer_price_lists
SET deleted_at = NOW()
WHERE customer_price_list_id = $1
`

func (q *Queries) DeleteCustomerPriceList(ctx context.Context, customerPriceListID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCustomerPriceList, customerPriceListID)
	return err
}

const getCustomerPriceListByID = `-- name: GetCustomerPriceListByID :one
SELECT cpl.customer_price_list_id, cpl.description, cpl.buyer_id, cpl.is_active, cpl.created_at, cpl.updated_at, cpl.deleted_at,
       b.buyer_code,
       b.buyer_name,
       b.phone_number,
       b.address,
       COALESCE(JSON_AGG(JSONB_BUILD_OBJECT(
         'customer_item_price_id', cip.customer_item_price_id,
         'item_id', cip.item_id,
         'item_default_name', it.item_default_name,
         'unit_id', cip.unit_id,
         'unit_name', u.unit_name,
         'unit_price_custom', cip.unit_price_custom,
         'position_key', cip.position_key
       ) ORDER BY cip.position_key ASC) FILTER (WHERE cip.customer_item_price_id IS NOT NULL), '[]')::JSONB AS item_prices
FROM customer_price_lists cpl
LEFT JOIN buyers b ON cpl.buyer_id = b.buyer_id
LEFT JOIN customer_item_prices cip ON cpl.customer_price_list_id = cip.customer_price_list_id
LEFT JOIN items it ON cip.item_id = it.item_id
LEFT JOIN units u ON cip.unit_id = u.unit_id
WHERE cpl.customer_price_list_id = $1 AND cpl.deleted_at IS NULL
GROUP BY cpl.customer_price_list_id, b.buyer_id, b.buyer_code, b.buyer_name, b.phone_number, b.address
`

type GetCustomerPriceListByIDRow struct {
	CustomerPriceListID uuid.UUID       `json:"customer_price_list_id"`
	Description         string          `json:"description"`
	BuyerID             uuid.NullUUID   `json:"buyer_id"`
	IsActive            sql.NullBool    `json:"is_active"`
	CreatedAt           sql.NullTime    `json:"created_at"`
	UpdatedAt           sql.NullTime    `json:"updated_at"`
	DeletedAt           sql.NullTime    `json:"deleted_at"`
	BuyerCode           sql.NullString  `json:"buyer_code"`
	BuyerName           sql.NullString  `json:"buyer_name"`
	PhoneNumber         sql.NullString  `json:"phone_number"`
	Address             sql.NullString  `json:"address"`
	ItemPrices          json.RawMessage `json:"item_prices"`
}

func (q *Queries) GetCustomerPriceListByID(ctx context.Context, customerPriceListID uuid.UUID) (GetCustomerPriceListByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCustomerPriceListByID, customerPriceListID)
	var i GetCustomerPriceListByIDRow
	err := row.Scan(
		&i.CustomerPriceListID,
		&i.Description,
		&i.BuyerID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.BuyerCode,
		&i.BuyerName,
		&i.PhoneNumber,
		&i.Address,
		&i.ItemPrices,
	)
	return i, err
}

const listCustomerPriceListsFiltered = `-- name: ListCustomerPriceListsFiltered :many
SELECT cpl.customer_price_list_id, cpl.description, cpl.buyer_id, cpl.is_active, cpl.created_at, cpl.updated_at, cpl.deleted_at,
       b.buyer_code,
       b.buyer_name,
       b.phone_number,
       b.address
FROM customer_price_lists cpl
LEFT JOIN buyers b ON cpl.buyer_id = b.buyer_id
WHERE cpl.deleted_at IS NULL
  AND ($1::UUID IS NULL OR cpl.buyer_id = $1::UUID)
  AND (
      $2::text IS NULL 
      OR (b.buyer_id IS NOT NULL AND (my_unaccent(b.buyer_name) ILIKE my_unaccent(concat('%', $2::text, '%')) OR my_unaccent(b.buyer_code) ILIKE my_unaccent(concat('%', $2::text, '%'))))
  )
  AND ($3::timestamptz IS NULL OR cpl.created_at >= $3::timestamptz)
  AND ($4::timestamptz IS NULL OR cpl.created_at <= $4::timestamptz)
ORDER BY 
  CASE WHEN $5::text = 'updated_at' AND $6::text = 'desc' THEN cpl.updated_at END DESC,
  CASE WHEN $5::text = 'updated_at' AND $6::text = 'asc' THEN cpl.updated_at END ASC,
  CASE WHEN $5::text = 'created_at' AND $6::text = 'desc' THEN cpl.created_at END DESC,
  CASE WHEN $5::text = 'created_at' AND $6::text = 'asc' THEN cpl.created_at END ASC,
  cpl.updated_at DESC
LIMIT $8
OFFSET $7
`

type ListCustomerPriceListsFilteredParams struct {
	BuyerID   uuid.NullUUID  `json:"buyer_id"`
	BuyerName sql.NullString `json:"buyer_name"`
	StartDate sql.NullTime   `json:"start_date"`
	EndDate   sql.NullTime   `json:"end_date"`
	SortBy    string         `json:"sort_by"`
	SortOrder string         `json:"sort_order"`
	OffsetVal int32          `json:"offset_val"`
	LimitVal  int32          `json:"limit_val"`
}

type ListCustomerPriceListsFilteredRow struct {
	CustomerPriceListID uuid.UUID      `json:"customer_price_list_id"`
	Description         string         `json:"description"`
	BuyerID             uuid.NullUUID  `json:"buyer_id"`
	IsActive            sql.NullBool   `json:"is_active"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	UpdatedAt           sql.NullTime   `json:"updated_at"`
	DeletedAt           sql.NullTime   `json:"deleted_at"`
	BuyerCode           sql.NullString `json:"buyer_code"`
	BuyerName           sql.NullString `json:"buyer_name"`
	PhoneNumber         sql.NullString `json:"phone_number"`
	Address             sql.NullString `json:"address"`
}

func (q *Queries) ListCustomerPriceListsFiltered(ctx context.Context, arg ListCustomerPriceListsFilteredParams) ([]ListCustomerPriceListsFilteredRow, error) {
	rows, err := q.db.QueryContext(ctx, listCustomerPriceListsFiltered,
		arg.BuyerID,
		arg.BuyerName,
		arg.StartDate,
		arg.EndDate,
		arg.SortBy,
		arg.SortOrder,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerPriceListsFilteredRow
	for rows.Next() {
		var i ListCustomerPriceListsFilteredRow
		if err := rows.Scan(
			&i.CustomerPriceListID,
			&i.Description,
			&i.BuyerID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.BuyerCode,
			&i.BuyerName,
			&i.PhoneNumber,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomerItemPricePos = `-- name: UpdateCustomerItemPricePos :exec
UPDATE customer_item_prices
SET position_key = $2
WHERE customer_item_price_id = $1
`

type UpdateCustomerItemPricePosParams struct {
	CustomerItemPriceID uuid.UUID `json:"customer_item_price_id"`
	PositionKey         string    `json:"position_key"`
}

func (q *Queries) UpdateCustomerItemPricePos(ctx context.Context, arg UpdateCustomerItemPricePosParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomerItemPricePos, arg.CustomerItemPriceID, arg.PositionKey)
	return err
}

const updateCustomerPriceList = `-- name: UpdateCustomerPriceList :one
UPDATE customer_price_lists
SET description = $2,
    buyer_id = $3,
    updated_at = NOW()
WHERE customer_price_list_id = $1 AND deleted_at IS NULL
RETURNING customer_price_list_id, description, buyer_id, is_active, created_at, updated_at, deleted_at
`

type UpdateCustomerPriceListParams struct {
	CustomerPriceListID uuid.UUID     `json:"customer_price_list_id"`
	Description         string        `json:"description"`
	BuyerID             uuid.NullUUID `json:"buyer_id"`
}

func (q *Queries) UpdateCustomerPriceList(ctx context.Context, arg UpdateCustomerPriceListParams) (CustomerPriceList, error) {
	row := q.db.QueryRowContext(ctx, updateCustomerPriceList, arg.CustomerPriceListID, arg.Description, arg.BuyerID)
	var i CustomerPriceList
	err := row.Scan(
		&i.CustomerPriceListID,
		&i.Description,
		&i.BuyerID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
