// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: print.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPrintJob = `-- name: CreatePrintJob :one
INSERT INTO print_queue (
    invoice_id,
    customer_price_list_id,
    print_type,
    priority_num,
    print_status
) VALUES (
    $1::uuid,
    $2::uuid,
    $3::print_type_enum,
    COALESCE($4::integer, 0),
    'Pending'
) RETURNING print_job_id, invoice_id, customer_price_list_id, print_status, print_type, retry_count, priority_num, created_at, printed_at
`

type CreatePrintJobParams struct {
	InvoiceID           uuid.NullUUID `json:"invoice_id"`
	CustomerPriceListID uuid.NullUUID `json:"customer_price_list_id"`
	PrintType           interface{}   `json:"print_type"`
	PriorityNum         sql.NullInt32 `json:"priority_num"`
}

func (q *Queries) CreatePrintJob(ctx context.Context, arg CreatePrintJobParams) (PrintQueue, error) {
	row := q.db.QueryRowContext(ctx, createPrintJob,
		arg.InvoiceID,
		arg.CustomerPriceListID,
		arg.PrintType,
		arg.PriorityNum,
	)
	var i PrintQueue
	err := row.Scan(
		&i.PrintJobID,
		&i.InvoiceID,
		&i.CustomerPriceListID,
		&i.PrintStatus,
		&i.PrintType,
		&i.RetryCount,
		&i.PriorityNum,
		&i.CreatedAt,
		&i.PrintedAt,
	)
	return i, err
}

const getPrintJobs = `-- name: GetPrintJobs :many
SELECT 
    pq.print_job_id,
    pq.invoice_id,
    pq.customer_price_list_id,
    pq.print_status,
    pq.print_type,
    pq.retry_count,
    pq.priority_num,
    pq.created_at,
    pq.printed_at,
    i.invoice_code,
    i.buyer_name_snapshot AS invoice_buyer_name,
    cpl.description AS price_list_description,
    b.buyer_name AS price_list_buyer_name
FROM print_queue pq
LEFT JOIN invoices i ON pq.invoice_id = i.invoice_id
LEFT JOIN customer_price_lists cpl ON pq.customer_price_list_id = cpl.customer_price_list_id
LEFT JOIN buyers b ON cpl.buyer_id = b.buyer_id
WHERE 
    ($1::text IS NULL OR $1::text = '' OR pq.print_status::text = $1::text)
    AND (
        $2::text IS NULL OR $2::text = 'Both' OR $2::text = ''
        OR ($2::text = 'Invoice' AND pq.invoice_id IS NOT NULL)
        OR ($2::text = 'PriceList' AND pq.customer_price_list_id IS NOT NULL)
    )
    AND (
        ($3::uuid IS NULL AND $4::uuid IS NULL)
        OR ($3::uuid IS NOT NULL AND $4::uuid IS NULL AND pq.invoice_id = $3::uuid)
        OR ($3::uuid IS NULL AND $4::uuid IS NOT NULL AND pq.customer_price_list_id = $4::uuid)
        OR ($3::uuid IS NOT NULL AND $4::uuid IS NOT NULL AND (pq.invoice_id = $3::uuid OR pq.customer_price_list_id = $4::uuid))
    )
ORDER BY 
    CASE pq.print_status::text
        WHEN 'Failed' THEN 1
        WHEN 'Printing' THEN 2
        WHEN 'Pending' THEN 3
        WHEN 'Cancelled' THEN 4
        WHEN 'Completed' THEN 5
        ELSE 6
    END ASC,
    pq.priority_num DESC, 
    pq.created_at ASC
LIMIT $6::integer
OFFSET $5::integer
`

type GetPrintJobsParams struct {
	PrintStatus         sql.NullString `json:"print_status"`
	QueueType           sql.NullString `json:"queue_type"`
	InvoiceID           uuid.NullUUID  `json:"invoice_id"`
	CustomerPriceListID uuid.NullUUID  `json:"customer_price_list_id"`
	OffsetVal           int32          `json:"offset_val"`
	LimitVal            int32          `json:"limit_val"`
}

type GetPrintJobsRow struct {
	PrintJobID           uuid.UUID      `json:"print_job_id"`
	InvoiceID            uuid.NullUUID  `json:"invoice_id"`
	CustomerPriceListID  uuid.NullUUID  `json:"customer_price_list_id"`
	PrintStatus          interface{}    `json:"print_status"`
	PrintType            interface{}    `json:"print_type"`
	RetryCount           sql.NullInt32  `json:"retry_count"`
	PriorityNum          sql.NullInt32  `json:"priority_num"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	PrintedAt            sql.NullTime   `json:"printed_at"`
	InvoiceCode          sql.NullString `json:"invoice_code"`
	InvoiceBuyerName     sql.NullString `json:"invoice_buyer_name"`
	PriceListDescription sql.NullString `json:"price_list_description"`
	PriceListBuyerName   sql.NullString `json:"price_list_buyer_name"`
}

func (q *Queries) GetPrintJobs(ctx context.Context, arg GetPrintJobsParams) ([]GetPrintJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPrintJobs,
		arg.PrintStatus,
		arg.QueueType,
		arg.InvoiceID,
		arg.CustomerPriceListID,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPrintJobsRow
	for rows.Next() {
		var i GetPrintJobsRow
		if err := rows.Scan(
			&i.PrintJobID,
			&i.InvoiceID,
			&i.CustomerPriceListID,
			&i.PrintStatus,
			&i.PrintType,
			&i.RetryCount,
			&i.PriorityNum,
			&i.CreatedAt,
			&i.PrintedAt,
			&i.InvoiceCode,
			&i.InvoiceBuyerName,
			&i.PriceListDescription,
			&i.PriceListBuyerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pollPrintJob = `-- name: PollPrintJob :one
SELECT print_job_id, invoice_id, customer_price_list_id, print_status, print_type, retry_count, priority_num, created_at, printed_at FROM print_queue
WHERE print_status = 'Pending'
ORDER BY priority_num DESC, created_at ASC
LIMIT 1
`

func (q *Queries) PollPrintJob(ctx context.Context) (PrintQueue, error) {
	row := q.db.QueryRowContext(ctx, pollPrintJob)
	var i PrintQueue
	err := row.Scan(
		&i.PrintJobID,
		&i.InvoiceID,
		&i.CustomerPriceListID,
		&i.PrintStatus,
		&i.PrintType,
		&i.RetryCount,
		&i.PriorityNum,
		&i.CreatedAt,
		&i.PrintedAt,
	)
	return i, err
}

const updatePrintJobStatus = `-- name: UpdatePrintJobStatus :one
UPDATE print_queue
SET 
    print_status = COALESCE($1::print_status_enum, print_status),
    retry_count = COALESCE($2::integer, retry_count),
    priority_num = COALESCE($3::integer, priority_num),
    printed_at = CASE WHEN $1::print_status_enum = 'Completed' THEN NOW() ELSE printed_at END
WHERE print_job_id = $4::uuid
RETURNING print_job_id, invoice_id, customer_price_list_id, print_status, print_type, retry_count, priority_num, created_at, printed_at
`

type UpdatePrintJobStatusParams struct {
	PrintStatus interface{}   `json:"print_status"`
	RetryCount  sql.NullInt32 `json:"retry_count"`
	PriorityNum sql.NullInt32 `json:"priority_num"`
	PrintJobID  uuid.UUID     `json:"print_job_id"`
}

func (q *Queries) UpdatePrintJobStatus(ctx context.Context, arg UpdatePrintJobStatusParams) (PrintQueue, error) {
	row := q.db.QueryRowContext(ctx, updatePrintJobStatus,
		arg.PrintStatus,
		arg.RetryCount,
		arg.PriorityNum,
		arg.PrintJobID,
	)
	var i PrintQueue
	err := row.Scan(
		&i.PrintJobID,
		&i.InvoiceID,
		&i.CustomerPriceListID,
		&i.PrintStatus,
		&i.PrintType,
		&i.RetryCount,
		&i.PriorityNum,
		&i.CreatedAt,
		&i.PrintedAt,
	)
	return i, err
}
